"""build-catalogue.py — idempotent generator for the Spec 14 Layer 1/3/4 catalogue.

Layers regenerated:
  - Layer 1 (envelopes)      <- sgs-db patterns table
  - Layer 3 (slot lists)     <- src/blocks/<slug>/block.json + render.php + role-templates
  - Layer 4 (inner-blocks)   <- sgs-db block_compositions table (re-parsed from theme/sgs-theme/patterns/*.php)

Layer 2 (`role-templates.json`) is hand-authored and is NOT regenerated by this
script — it lives at output/role-templates.json and is the dispatch table
extract.py (P4) reads.

Usage:
  python build-catalogue.py            # regenerate all three layers
  python build-catalogue.py --check    # rebuild in /tmp then diff vs committed (idempotency test)

The companion `step2_3_4_layer1_3_4.py` and `step6_layer3.py` modules contain
the layer-specific logic; this script only orchestrates.

Future: hook into /sgs-update Stage 5 so the catalogue stays current as blocks evolve.
"""
from __future__ import annotations
import argparse, filecmp, json, os, shutil, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..'))
OUT_DIR = os.path.join(HERE, 'output')

# Import the layer-specific generators
sys.path.insert(0, HERE)
import importlib.util


def _load_module(name: str, path: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def build(out_dir: str | None = None) -> None:
    """Regenerate Layers 1, 3, 4 into *out_dir* (default: ./output)."""
    out_dir = out_dir or OUT_DIR
    os.makedirs(out_dir, exist_ok=True)

    # Step 2+3+4 — Layer 1 + populate block_compositions + Layer 4
    s234 = _load_module('s234', os.path.join(HERE, 'step2_3_4_layer1_3_4.py'))
    s234.OUT_DIR = out_dir
    import sqlite3
    db = sqlite3.connect(s234.DB_PATH)
    n1 = s234.step2_layer1(db)
    n3, skipped = s234.step3_block_compositions(db)
    n4 = s234.step4_layer4(db)
    db.close()

    # Step 6 — Layer 3
    s6 = _load_module('s6', os.path.join(HERE, 'step6_layer3.py'))
    s6.OUT_DIR = out_dir
    s6.main()

    print(f'Catalogue regenerated:')
    print(f'  Layer 1 envelopes:           {n1}')
    print(f'  block_compositions populated: {n3} (skipped: {len(skipped)})')
    print(f'  Layer 4 entries:             {n4}')
    print(f'  Output dir: {out_dir}')


def check_idempotent() -> int:
    """Build into a temp dir and diff against the committed output."""
    tmp = tempfile.mkdtemp(prefix='sgs-catalogue-check-')
    try:
        build(out_dir=tmp)
        files = ['layer-1-envelopes.json', 'layer-3-internal-elements.json', 'layer-4-inner-blocks.json']
        diffs = []
        for f in files:
            a = os.path.join(OUT_DIR, f)
            b = os.path.join(tmp, f)
            if not os.path.exists(a):
                print(f'  MISSING committed: {f}')
                diffs.append(f)
                continue
            if not filecmp.cmp(a, b, shallow=False):
                print(f'  DIFF: {f}')
                diffs.append(f)
            else:
                print(f'  IDENTICAL: {f}')
        if diffs:
            print(f'\nIdempotency FAIL — {len(diffs)} file(s) differ.')
            return 1
        print('\nIdempotency PASS — all files byte-identical on re-run.')
        return 0
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def main() -> int:
    parser = argparse.ArgumentParser(description='SGS Spec 14 Layer 1/3/4 catalogue generator')
    parser.add_argument('--check', action='store_true', help='Build into temp dir + diff against committed (idempotency test)')
    args = parser.parse_args()
    if args.check:
        return check_idempotent()
    build()
    return 0


if __name__ == '__main__':
    sys.exit(main())
