<?php
/**
 * Main plugin class — auto-discovers and registers all blocks.
 *
 * @package SGS\Blocks
 */

namespace SGS\Blocks;

defined( 'ABSPATH' ) || exit;

final class SGS_Blocks {

	private static ?self $instance = null;

	public static function instance(): self {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	private function __construct() {
		add_action( 'init', [ $this, 'register_blocks' ] );
		add_action( 'init', [ $this, 'register_block_styles' ] );
		add_action( 'wp_enqueue_scripts', [ $this, 'enqueue_frontend_assets' ] );
		add_action( 'enqueue_block_editor_assets', [ $this, 'enqueue_editor_extensions' ] );

		// Post Grid REST endpoint for AJAX pagination and category filtering.
		require_once SGS_BLOCKS_PATH . 'includes/class-post-grid-rest.php';
		Post_Grid_REST::register();

		// Global Block Defaults — REST API, editor injection, admin settings page.
		require_once SGS_BLOCKS_PATH . 'includes/class-block-defaults.php';
		Block_Defaults::register();

		// Image Controls extension — objectPosition / maxWidth / per-breakpoint height.
		require_once SGS_BLOCKS_PATH . 'includes/image-controls.php';

		// Pattern slug backward-compat shim (sgs-theme/ → sgs/ aliases, 1-cycle deprecation).
		require_once SGS_BLOCKS_PATH . 'includes/class-pattern-slug-shim.php';
		Pattern_Slug_Shim::register();

		// Block variations — generated by /sgs-clone essence-match detector (P2.iii).
		// Loads every sgs-*-variations.php file in includes/variations/.
		require_once SGS_BLOCKS_PATH . 'includes/variations/class-sgs-block-variations.php';
		Sgs_Block_Variations::load();

		// Mobile-nav inserter scope — removes sgs/mobile-nav + sgs/mobile-nav-toggle
		// from the post/page inserter; leaves them available in the Site Editor.
		require_once SGS_BLOCKS_PATH . 'includes/mobile-nav-inserter-scope.php';

		// Product Block Bindings source (sgs-product/field) — backs the
		// sgs/product-card Bound mode with WooCommerce or sgs_product CPT data.
		require_once SGS_BLOCKS_PATH . 'includes/class-product-bindings.php';
		Product_Bindings::register();

		// Cart proxy (POST /sgs/v1/cart/add-item) — validates (CSRF + IDOR +
		// attribute-match + stock + qty-cap + rate-limit) then adds in-process
		// via WC()->cart. Server-authoritative price + stock (Spec 27 FR-27-G*).
		require_once SGS_BLOCKS_PATH . 'includes/class-cart-proxy.php';
		Cart_Proxy::register();

		// Product Search REST (GET /sgs/v1/product-search) — guest typeahead
		// with zero data leakage. Security chain: global circuit breaker →
		// per-IP rate-limit → input guards → visibility tax_query (fail-closed)
		// → result-level re-gate → fixed {id,title,permalink,thumbnail} shape.
		// FR-30-5 build contract: reports/FR-30-5-search-design.md.
		require_once SGS_BLOCKS_PATH . 'includes/class-product-search-rest.php';
		Product_Search_REST::register();

		// Smart Bulk Pricing P3 (Spec 28 FR-28-3/4/6/10/11) — PREVIEW: cascade
		// site→category→product, WC settings tab, term/product fields, and POST
		// /sgs/v1/pack-pricing/preview. The fields/settings files self-register
		// their hooks on require; the REST controller registers explicitly.
		require_once SGS_BLOCKS_PATH . 'includes/class-pack-pricing-preview.php';
		Pack_Pricing_Preview::register();
		// Smart Bulk Pricing P4 (Spec 28 FR-28-5/10/11/13/14) — the WC-WRITE path.
		// Registers POST /sgs/v1/pack-pricing/{apply,revert,release-lock}. The
		// ONLY write trigger is the explicit two-step "Apply prices to your live
		// shop" button — never an auto save_post hook.
		require_once SGS_BLOCKS_PATH . 'includes/class-pack-pricing-apply.php';
		Pack_Pricing_Apply::register();
		require_once SGS_BLOCKS_PATH . 'includes/pack-pricing-settings.php';
		require_once SGS_BLOCKS_PATH . 'includes/pack-pricing-category-fields.php';
		require_once SGS_BLOCKS_PATH . 'includes/pack-pricing-product-fields.php';
	}

	/**
	 * Auto-discover and register all blocks from the build directory.
	 *
	 * Each subdirectory of build/blocks/ that contains a block.json
	 * is automatically registered. No manual registration needed —
	 * just create the block folder, build, and it appears.
	 */
	public function register_blocks(): void {
		$blocks_dir = SGS_BLOCKS_PATH . 'build/blocks';

		if ( ! is_dir( $blocks_dir ) ) {
			return;
		}

		$block_dirs = array_filter(
			scandir( $blocks_dir ),
			fn( string $item ): bool => is_dir( $blocks_dir . '/' . $item )
				&& ! \in_array( $item, [ '.', '..' ], true )
		);

		foreach ( $block_dirs as $block ) {
			$block_json = $blocks_dir . '/' . $block . '/block.json';

			if ( file_exists( $block_json ) ) {
				register_block_type( $block_json );

				// Wire WP 7.0 script-module translations for blocks that use viewScriptModule.
				// Infrastructure only — no translation .json files required until the first
				// non-English client onboards (Decision 23c, Phase 6).
				// Module ID convention: @sgs/<block-slug>/view (WP auto-registers this from
				// viewScriptModule in block.json via WP_Script_Modules::register()).
				$block_json_data = json_decode( file_get_contents( $block_json ), true ); // phpcs:ignore WordPress.WP.AlternativeFunctions
				if ( ! empty( $block_json_data['viewScriptModule'] ) && function_exists( 'wp_set_script_module_translations' ) ) {
					$module_id = '@sgs/' . $block . '/view';
					wp_set_script_module_translations( $module_id, 'sgs-blocks', SGS_BLOCKS_PATH . 'languages' );
				}
			}
		}
	}

	/**
	 * Enqueue block extensions for the editor.
	 *
	 * Loads the compiled extensions bundle (device visibility, animation)
	 * in the block editor so that the inspector controls appear for all blocks.
	 * The asset file is auto-generated by @wordpress/scripts and contains
	 * the correct WordPress script dependencies.
	 */
	public function enqueue_editor_extensions(): void {
		// Expose icon-asset URLs to the shared IconPicker component. Attached to
		// the always-present 'wp-blocks' editor handle so every block script can
		// read window.sgsBlocksData regardless of bundle load order. The JSON
		// assets are fetched on demand by the picker modal (editor only).
		$icons_dir = SGS_BLOCKS_PATH . 'assets/icons/';
		$icons_url = SGS_BLOCKS_URL . 'assets/icons/';
		$icon_ver  = static function ( string $file ) use ( $icons_dir ): string {
			$path = $icons_dir . $file;
			return file_exists( $path ) ? (string) filemtime( $path ) : '0';
		};
		wp_add_inline_script(
			'wp-blocks',
			'window.sgsBlocksData = window.sgsBlocksData || {};' .
			'window.sgsBlocksData.iconAssets = ' . wp_json_encode(
				array(
					'lucide'     => $icons_url . 'lucide-icons.json?ver=' . $icon_ver( 'lucide-icons.json' ),
					'lucideTags' => $icons_url . 'lucide-tags.json?ver=' . $icon_ver( 'lucide-tags.json' ),
					'emoji'      => $icons_url . 'emoji.json?ver=' . $icon_ver( 'emoji.json' ),
					'wpIcons'    => $icons_url . 'wp-icons.json?ver=' . $icon_ver( 'wp-icons.json' ),
				)
			) . ';',
			'before'
		);

		$asset_file = SGS_BLOCKS_PATH . 'build/extensions/index.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		wp_enqueue_script(
			'sgs-block-extensions',
			SGS_BLOCKS_URL . 'build/extensions/index.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		// Load the extensions CSS in the editor too, so visibility
		// classes are correctly applied in the editor preview.
		$css_file = SGS_BLOCKS_PATH . 'assets/css/extensions.css';
		if ( file_exists( $css_file ) ) {
			wp_enqueue_style(
				'sgs-extensions-editor',
				SGS_BLOCKS_URL . 'assets/css/extensions.css',
				[],
				SGS_BLOCKS_VERSION
			);
		}
	}

	/**
	 * Enqueue frontend CSS and JS for extensions.
	 *
	 * Animation CSS and IntersectionObserver script load on every page.
	 * Combined weight is < 2KB — negligible impact on performance.
	 */
	public function enqueue_frontend_assets(): void {
		$css_file = SGS_BLOCKS_PATH . 'assets/css/extensions.css';
		if ( file_exists( $css_file ) ) {
			wp_enqueue_style(
				'sgs-extensions',
				SGS_BLOCKS_URL . 'assets/css/extensions.css',
				[],
				SGS_BLOCKS_VERSION
			);
		}

		$js_file = SGS_BLOCKS_PATH . 'assets/js/animation-observer.js';
		if ( file_exists( $js_file ) ) {
			wp_enqueue_script(
				'sgs-animation-observer',
				SGS_BLOCKS_URL . 'assets/js/animation-observer.js',
				[],
				SGS_BLOCKS_VERSION,
				true
			);
		}

		$scroll_js = SGS_BLOCKS_PATH . 'assets/js/scroll-progress.js';
		if ( file_exists( $scroll_js ) ) {
			wp_enqueue_script(
				'sgs-scroll-progress',
				SGS_BLOCKS_URL . 'assets/js/scroll-progress.js',
				[],
				SGS_BLOCKS_VERSION,
				true
			);
		}

		$tilt_js = SGS_BLOCKS_PATH . 'assets/js/tilt-3d.js';
		if ( file_exists( $tilt_js ) ) {
			wp_enqueue_script(
				'sgs-tilt-3d',
				SGS_BLOCKS_URL . 'assets/js/tilt-3d.js',
				[],
				SGS_BLOCKS_VERSION,
				true
			);
		}

		$ripple_js = SGS_BLOCKS_PATH . 'assets/js/ripple.js';
		if ( file_exists( $ripple_js ) ) {
			wp_enqueue_script(
				'sgs-ripple',
				SGS_BLOCKS_URL . 'assets/js/ripple.js',
				[],
				SGS_BLOCKS_VERSION,
				true
			);
		}

		$parallax_js = SGS_BLOCKS_PATH . 'assets/js/parallax.js';
		if ( file_exists( $parallax_js ) ) {
			wp_register_script(
				'sgs-parallax',
				SGS_BLOCKS_URL . 'assets/js/parallax.js',
				array(),
				SGS_BLOCKS_VERSION,
				array(
					'strategy'  => 'defer',
					'in_footer' => true,
				)
			);
			wp_enqueue_script( 'sgs-parallax' );
		}

		// High-contrast mode baseline styles for all SGS blocks.
		$contrast_file = SGS_BLOCKS_PATH . 'assets/css/contrast.css';
		if ( file_exists( $contrast_file ) ) {
			wp_enqueue_style(
				'sgs-contrast',
				SGS_BLOCKS_URL . 'assets/css/contrast.css',
				[],
				SGS_BLOCKS_VERSION
			);
		}
	}

	/**
	 * Register block style variations for SGS blocks.
	 *
	 * Styles are registered here so the compiled block style-index.css
	 * (which is enqueued automatically by register_block_type) loads the
	 * scoped CSS for each variation without a separate stylesheet.
	 */
	public function register_block_styles(): void {
		register_block_style(
			'sgs/social-icons',
			array(
				'name'  => 'social-icons-footer',
				'label' => __( 'Footer (plain, light)', 'sgs-blocks' ),
			)
		);
	}
}
