<?php
/**
 * SGS Google Merchant Feed — channel wrapper + brand resolution (FR-27-F2).
 *
 * Extracted from class-product-feed.php to keep that file under the SGS
 * 300-line limit. Holds the RSS 2.0 channel envelope builder and the g:brand
 * resolution chain.
 *
 * @package SGS\Blocks
 * @since   1.15.0
 */

namespace SGS\Blocks;

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/class-product-feed-items.php';

/**
 * Channel envelope + brand resolution for the Merchant feed.
 *
 * @internal Used only by Product_Feed.
 */
final class Product_Feed_Channel {

	/**
	 * Wrap per-item fragments in a complete RSS 2.0 + GMC namespace document.
	 *
	 * @param string $items_xml Concatenated <item> fragments (may be '').
	 * @return string Full XML document.
	 */
	public static function wrap_channel( string $items_xml ): string {
		// Decode WP's display-filter HTML entities BEFORE XML-escaping, or the
		// output carries literal "&amp;#039;" text (double-escape, live-caught).
		$site_name = Product_Feed_Items::xml_esc( \html_entity_decode( \get_bloginfo( 'name' ), ENT_QUOTES | ENT_HTML5, 'UTF-8' ) );
		$site_url  = Product_Feed_Items::xml_esc( \esc_url_raw( \home_url( '/' ) ) );
		$generated = \gmdate( DATE_RFC2822 );

		$xml  = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
		$xml .= '<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">' . "\n";
		$xml .= '<channel>' . "\n";
		$xml .= '<title>' . $site_name . ' &#8212; Google Merchant Feed</title>' . "\n";
		$xml .= '<link>' . $site_url . '</link>' . "\n";
		$xml .= '<description>Google Merchant Center product feed generated by SGS Blocks.</description>' . "\n";
		$xml .= '<!-- Generated: ' . \esc_html( $generated ) . ' -->' . "\n";
		$xml .= $items_xml;
		$xml .= '</channel>' . "\n";
		$xml .= '</rss>' . "\n";

		return $xml;
	}

	/**
	 * Resolve brand name from a product — first hit wins.
	 *
	 * Priority: (1) product_brand taxonomy → first term name;
	 * (2) 'brand' product attribute → first value;
	 * (3) site name fallback (FR-27-F2: g:brand must never be empty).
	 *
	 * @param \WC_Product $product Product object.
	 * @return string Brand name (never empty — site name is the ultimate fallback).
	 */
	public static function resolve_brand( \WC_Product $product ): string {
		if ( \taxonomy_exists( 'product_brand' ) ) {
			$terms = \get_the_terms( $product->get_id(), 'product_brand' );
			if ( $terms && ! \is_wp_error( $terms ) && ! empty( $terms ) ) {
				return \sanitize_text_field( $terms[0]->name );
			}
		}

		$attr = $product->get_attribute( 'brand' );
		if ( '' !== (string) $attr ) {
			$parts = \explode( ',', (string) $attr );
			$first = \trim( \sanitize_text_field( $parts[0] ) );
			if ( '' !== $first ) {
				return $first;
			}
		}

		// Entity-decode the display-filtered site name (g:brand is XML-escaped later).
		return \trim( \sanitize_text_field( \html_entity_decode( (string) \get_bloginfo( 'name' ), ENT_QUOTES | ENT_HTML5, 'UTF-8' ) ) );
	}
}
