<?php
/**
 * AUTO-GENERATED by scripts/generate-extension-attributes.js — DO NOT EDIT BY HAND.
 * Regenerate with `npm run build` (or `node scripts/generate-extension-attributes.js`).
 * Single source of truth = the `sgs*` attribute definitions in src/blocks/extensions/*.js.
 *
 * @package SGS\Blocks
 */

return array(
	'sgsAnimation' => array( 'type' => 'string' ),
	'sgsAnimationDelay' => array( 'type' => 'string' ),
	'sgsAnimationDuration' => array( 'type' => 'string' ),
	'sgsAnimationEasing' => array( 'type' => 'string' ),
	'sgsBlockLink' => array( 'type' => 'string' ),
	'sgsBlockLinkTarget' => array( 'type' => 'boolean' ),
	'sgsClickEffect' => array( 'type' => 'string' ),
	'sgsClickRippleColour' => array( 'type' => 'string' ),
	'sgsClickRippleDuration' => array( 'type' => 'number' ),
	'sgsConditionDateEnd' => array( 'type' => 'string' ),
	'sgsConditionDateStart' => array( 'type' => 'string' ),
	'sgsConditionDays' => array( 'type' => 'array' ),
	'sgsConditionLoggedIn' => array( 'type' => 'string' ),
	'sgsConditionReferrer' => array( 'type' => 'string' ),
	'sgsConditionUrlParam' => array( 'type' => 'string' ),
	'sgsConditionUserRole' => array( 'type' => 'array' ),
	'sgsCustomCss' => array( 'type' => 'string' ),
	'sgsFocusRing' => array( 'type' => 'boolean' ),
	'sgsHeightDesktop' => array( 'type' => 'number' ),
	'sgsHeightMobile' => array( 'type' => 'number' ),
	'sgsHeightTablet' => array( 'type' => 'number' ),
	'sgsHeightUnit' => array( 'type' => 'string' ),
	'sgsHideOnDesktop' => array( 'type' => 'boolean' ),
	'sgsHideOnMobile' => array( 'type' => 'boolean' ),
	'sgsHideOnTablet' => array( 'type' => 'boolean' ),
	'sgsHoverBgColour' => array( 'type' => 'string' ),
	'sgsHoverBorderAccent' => array( 'type' => 'boolean' ),
	'sgsHoverBorderColour' => array( 'type' => 'string' ),
	'sgsHoverDuration' => array( 'type' => 'string' ),
	'sgsHoverEasing' => array( 'type' => 'string' ),
	'sgsHoverGrayscale' => array( 'type' => 'boolean' ),
	'sgsHoverImageZoom' => array( 'type' => 'boolean' ),
	'sgsHoverScale' => array( 'type' => 'number' ),
	'sgsHoverScalePreset' => array( 'type' => 'string' ),
	'sgsHoverShadow' => array( 'type' => 'string' ),
	'sgsHoverTextColour' => array( 'type' => 'string' ),
	'sgsHoverTilt3D' => array( 'type' => 'boolean' ),
	'sgsMarginBottom' => array( 'type' => 'string' ),
	'sgsMarginTop' => array( 'type' => 'string' ),
	'sgsMaxWidth' => array( 'type' => 'string' ),
	'sgsObjectPosition' => array( 'type' => 'string' ),
	'sgsPaddingBottom' => array( 'type' => 'string' ),
	'sgsPaddingTop' => array( 'type' => 'string' ),
	'sgsParallax' => array( 'type' => 'string' ),
	'sgsParallaxStrength' => array( 'type' => 'number' ),
	'sgsStaggerDelay' => array( 'type' => 'number' ),
);
