<?php
/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Source: src/components/MediaElementControls.js
 *         ( MEDIA_ATTR_TYPES + MEDIA_BASES )
 * Regenerate: node scripts/generate-media-attributes.mjs
 * Gate:       node scripts/generate-media-attributes.mjs --check
 *
 * Four maps, mirrored for the server so register_block_type_args() registers
 * exactly the schema the editor injects:
 *
 *   bases   base -> declared type
 *   groups  vocabulary group -> its bases
 *   tiered  the bases that carry Tablet/Mobile siblings
 *   atoms   atom id -> its bases (this is what drives SELECTIVE injection)
 *
 * Editing this by hand makes the two sides disagree - and a type mismatch does
 * not error, it makes WordPress silently coerce the stored value back to its
 * default, deleting the client's media on load.
 *
 * @package SGS\Blocks
 */

return array(
	'bases'  => array(
		"AnimationDuration"        => "number",
		"AspectRatio"              => "string",
		"Attachment"               => "string",
		"BorderColour"             => "string",
		"BorderColourGradient"     => "string",
		"BorderRadius"             => "object",
		"BorderStyle"              => "string",
		"BorderWidth"              => "object",
		"BoxShadow"                => "string",
		"BoxShadowColour"          => "string",
		"BoxShadowColourHover"     => "string",
		"Caption"                  => "string",
		"CaptionTag"               => "string",
		"DecorMedia"               => "object",
		"Height"                   => "object",
		"HeightUnit"               => "string",
		"ImageAlt"                 => "string",
		"ImageDecorative"          => "boolean",
		"ImageHeight"              => "number",
		"ImageId"                  => "integer",
		"ImageUrl"                 => "string",
		"ImageWidth"               => "number",
		"KenBurns"                 => "boolean",
		"LinkOpensNewTab"          => "boolean",
		"LinkRel"                  => "string",
		"LinkUrl"                  => "string",
		"MaxHeight"                => "object",
		"MaxHeightUnit"            => "string",
		"MaxWidth"                 => "object",
		"MaxWidthPercent"          => "number",
		"MaxWidthUnit"             => "string",
		"MediaSizing"              => "string",
		"MediaType"                => "string",
		"MinHeight"                => "object",
		"ObjectFit"                => "string",
		"ObjectPosition"           => "string",
		"Opacity"                  => "number",
		"OverlayBlendMode"         => "string",
		"OverlayColour"            => "string",
		"OverlayColourHover"       => "string",
		"OverlayGradient"          => "string",
		"OverlayGradientHover"     => "string",
		"OverlayOpacity"           => "number",
		"Padding"                  => "object",
		"Parallax"                 => "boolean",
		"Position"                 => "string",
		"Repeat"                   => "string",
		"Shape"                    => "string",
		"Size"                     => "string",
		"SvgAnimation"             => "string",
		"SvgAnimationSpeed"        => "string",
		"SvgContent"               => "string",
		"SvgMinHeight"             => "string",
		"SvgOpacity"               => "number",
		"SvgPosition"              => "string",
		"SvgTextShadow"            => "boolean",
		"Thumbnail"                => "object",
		"ThumbnailId"              => "integer",
		"VideoAlt"                 => "string",
		"VideoAutoplay"            => "boolean",
		"VideoCaptionsId"          => "integer",
		"VideoCaptionsLabel"       => "string",
		"VideoCaptionsSrcLang"     => "string",
		"VideoCaptionsUrl"         => "string",
		"VideoControls"            => "boolean",
		"VideoId"                  => "integer",
		"VideoLazyLoad"            => "boolean",
		"VideoLoop"                => "boolean",
		"VideoMimeType"            => "string",
		"VideoMuted"               => "boolean",
		"VideoPlaysInline"         => "boolean",
		"VideoSource"              => "string",
		"VideoUrl"                 => "string",
		"Width"                    => "object",
		"WidthUnit"                => "string",
	),
	'groups' => array(
		"behaviour"    => array(
			"VideoAutoplay",
			"VideoLoop",
			"VideoMuted",
			"VideoControls",
			"VideoPlaysInline",
			"VideoLazyLoad",
			"VideoCaptionsId",
			"VideoCaptionsUrl",
			"VideoCaptionsLabel",
			"VideoCaptionsSrcLang",
		),
		"caption"      => array(
			"Caption",
			"CaptionTag",
		),
		"fit"          => array(
			"ObjectFit",
			"Size",
		),
		"focal"        => array(
			"ObjectPosition",
			"Position",
			"Repeat",
			"Attachment",
		),
		"intrinsic"    => array(
			"ImageWidth",
			"ImageHeight",
		),
		"link"         => array(
			"LinkUrl",
			"LinkOpensNewTab",
			"LinkRel",
		),
		"meaning"      => array(
			"ImageAlt",
			"VideoAlt",
			"ImageDecorative",
		),
		"motion"       => array(
			"KenBurns",
			"Parallax",
			"AnimationDuration",
		),
		"opacity"      => array(
			"Opacity",
		),
		"overlay"      => array(
			"OverlayColour",
			"OverlayColourHover",
			"OverlayGradient",
			"OverlayGradientHover",
			"OverlayOpacity",
			"OverlayBlendMode",
		),
		"padding"      => array(
			"Padding",
		),
		"shadow"       => array(
			"BoxShadow",
			"BoxShadowColour",
			"BoxShadowColourHover",
		),
		"shape"        => array(
			"MediaSizing",
			"AspectRatio",
			"Shape",
			"Height",
			"HeightUnit",
			"MaxHeight",
			"MaxHeightUnit",
			"MaxWidth",
			"MaxWidthUnit",
			"MaxWidthPercent",
			"MinHeight",
			"Width",
			"WidthUnit",
			"BorderRadius",
			"BorderWidth",
			"BorderStyle",
			"BorderColour",
			"BorderColourGradient",
		),
		"source"       => array(
			"ImageId",
			"ImageUrl",
			"VideoId",
			"VideoUrl",
			"SvgContent",
			"Thumbnail",
			"ThumbnailId",
		),
		"svg"          => array(
			"SvgAnimation",
			"SvgAnimationSpeed",
			"SvgOpacity",
			"SvgPosition",
			"SvgMinHeight",
			"SvgTextShadow",
		),
		"type"         => array(
			"MediaType",
			"VideoSource",
			"VideoMimeType",
		),
	),
	'tiered' => array(
		"BorderRadius",
		"Height",
		"ImageId",
		"ImageUrl",
		"MinHeight",
		"ObjectFit",
		"ObjectPosition",
		"OverlayOpacity",
		"Padding",
		"SvgContent",
		"Thumbnail",
		"ThumbnailId",
		"VideoAutoplay",
		"VideoCaptionsId",
		"VideoCaptionsLabel",
		"VideoCaptionsSrcLang",
		"VideoCaptionsUrl",
		"VideoControls",
		"VideoId",
		"VideoLazyLoad",
		"VideoLoop",
		"VideoMuted",
		"VideoPlaysInline",
		"VideoUrl",
		"Width",
	),
	'atoms'  => array(
		"box-shape"          => array(
			"MediaSizing",
			"AspectRatio",
			"Shape",
			"Height",
			"HeightUnit",
			"MaxHeight",
			"MaxHeightUnit",
			"MaxWidth",
			"MaxWidthUnit",
			"MaxWidthPercent",
			"MinHeight",
			"Width",
			"WidthUnit",
			"BorderRadius",
			"BorderWidth",
			"BorderStyle",
			"BorderColour",
			"BorderColourGradient",
		),
		"caption"            => array(
			"Caption",
			"CaptionTag",
		),
		"focal-point"        => array(
			"ObjectPosition",
			"Position",
			"Repeat",
			"Attachment",
		),
		"intrinsic"          => array(
			"ImageWidth",
			"ImageHeight",
		),
		"link"               => array(
			"LinkUrl",
			"LinkOpensNewTab",
			"LinkRel",
		),
		"meaning"            => array(
			"ImageAlt",
			"VideoAlt",
			"ImageDecorative",
		),
		"media-padding"      => array(
			"Padding",
		),
		"media-type"         => array(
			"MediaType",
			"VideoSource",
			"VideoMimeType",
		),
		"motion"             => array(
			"KenBurns",
			"Parallax",
			"AnimationDuration",
		),
		"object-fit"         => array(
			"ObjectFit",
			"Size",
		),
		"opacity"            => array(
			"Opacity",
		),
		"overlay"            => array(
			"OverlayColour",
			"OverlayColourHover",
			"OverlayGradient",
			"OverlayGradientHover",
			"OverlayOpacity",
			"OverlayBlendMode",
		),
		"shadow"             => array(
			"BoxShadow",
			"BoxShadowColour",
			"BoxShadowColourHover",
		),
		"source"             => array(
			"ImageId",
			"ImageUrl",
			"VideoId",
			"VideoUrl",
			"SvgContent",
			"Thumbnail",
			"ThumbnailId",
		),
		"svg-presentation"   => array(
			"SvgAnimation",
			"SvgAnimationSpeed",
			"SvgOpacity",
			"SvgPosition",
			"SvgMinHeight",
			"SvgTextShadow",
		),
		"video-behaviour"    => array(
			"VideoAutoplay",
			"VideoLoop",
			"VideoMuted",
			"VideoControls",
			"VideoPlaysInline",
			"VideoLazyLoad",
			"VideoCaptionsId",
			"VideoCaptionsUrl",
			"VideoCaptionsLabel",
			"VideoCaptionsSrcLang",
		),
	),
);
