'use strict';

// Report is generated by iterating the rule REGISTRY (rules.json order),
// never a second hand-written order list — this is the direct mitigation for
// H7 (db-consistency/run.py's Check #8, collected but never printed because
// it was missing from a separate _CHECK_ORDER list).

function printHuman( { table, results, driftFindings, parseErrorFindings, rosterInfo, stats } ) {
	console.log( `[inspector-scan] Spec 35 — ${ table.rules.length } rule(s) declared in rules.json` );
	console.log(
		`DENOMINATOR: roster ${ rosterInfo.denominator.roster } / disk ${ rosterInfo.denominator.disk } / union ${ rosterInfo.denominator.union }`
	);
	console.log( `PARSE CACHE: ${ stats.reads } file read(s), ${ stats.parses } AST parse(s) this run` );
	console.log( '' );

	if ( driftFindings.length ) {
		console.log( `ROSTER-DRIFT (${ driftFindings.length })` );
		for ( const f of driftFindings ) {
			console.log( `  [${ f.severity.toUpperCase() }] ${ f.block || '(scanner)' } — ${ f.detail }` );
			console.log( `    FIX: ${ f.fix }` );
		}
	} else {
		console.log( 'ROSTER-DRIFT: none — roster.json and src/blocks/ agree.' );
	}
	console.log( '' );

	if ( parseErrorFindings.length ) {
		console.log( `PARSE-ERROR (${ parseErrorFindings.length })` );
		for ( const f of parseErrorFindings ) {
			console.log( `  [${ f.severity.toUpperCase() }] ${ f.block } ${ f.file } — ${ f.detail }` );
			console.log( `    FIX: ${ f.fix }` );
		}
	} else {
		console.log( 'PARSE-ERROR: none — every edit.js on the roster parsed successfully.' );
	}
	console.log( '' );

	for ( const r of results ) {
		const { ruleDef, findings, runError, skipped } = r;
		if ( skipped ) {
			console.log( `RULE ${ ruleDef.id.padEnd( 30 ) } [OFF]       ${ ruleDef.offReason || '' }` );
			continue;
		}
		if ( runError ) {
			console.log(
				`RULE ${ ruleDef.id.padEnd( 30 ) } [${ ruleDef.mode.toUpperCase() }] RUN ERROR: ${ runError }`
			);
			continue;
		}
		const flagged = findings.filter( ( f ) => f.status === 'FLAGGED' ).length;
		const baselined = findings.filter( ( f ) => f.status === 'BASELINED' ).length;
		console.log(
			`RULE ${ ruleDef.id.padEnd( 30 ) } [${ ruleDef.mode.toUpperCase().padEnd( 8 ) }] ${ flagged } flagged · ${ baselined } baselined`
		);
		if ( ruleDef.mode === 'advisory' && ruleDef.advisoryReason ) {
			console.log( `  advisory reason: ${ ruleDef.advisoryReason }` );
		}
		for ( const f of findings ) {
			if ( f.status !== 'FLAGGED' ) continue;
			console.log( `    ${ f.block || f.file }${ f.line ? ':' + f.line : '' }` );
			console.log( `      ${ f.detail }` );
			console.log( `      FIX: ${ f.fix }` );
		}
	}

	console.log( '' );
	const gatingRules = results.filter( ( r ) => r.ruleDef.mode === 'gate' );
	const gatingFindings = gatingRules.reduce(
		( n, r ) => n + r.findings.filter( ( f ) => f.status === 'FLAGGED' ).length,
		0
	);
	const advisoryRules = results.filter( ( r ) => r.ruleDef.mode === 'advisory' );
	const advisoryFindings = advisoryRules.reduce(
		( n, r ) => n + r.findings.filter( ( f ) => f.status === 'FLAGGED' ).length,
		0
	);
	const offRules = results.filter( ( r ) => r.ruleDef.mode === 'off' );
	console.log(
		`SUMMARY  gate rules: ${ gatingRules.length } · gating findings: ${ gatingFindings }`
	);
	console.log(
		`         advisory rules: ${ advisoryRules.length } · advisory findings: ${ advisoryFindings } (never gate)`
	);
	console.log( `         off: ${ offRules.length }` );
}

function printJson( { table, results, driftFindings, parseErrorFindings, rosterInfo, stats } ) {
	const out = {
		_meta: {
			denominator: rosterInfo.denominator,
			stats,
			modes: Object.fromEntries( table.rules.map( ( r ) => [ r.id, r.mode ] ) ),
		},
		driftFindings,
		parseErrorFindings,
		rules: results.map( ( r ) => ( {
			id: r.ruleDef.id,
			mode: r.ruleDef.mode,
			runError: r.runError || null,
			findings: r.findings,
		} ) ),
	};
	console.log( JSON.stringify( out, null, 2 ) );
}

module.exports = { printHuman, printJson };
