#!/usr/bin/env python3
"""2026-09-14-nav-menu-split.py — census + codemod for splitting `sgs/nav-menu` into
`sgs/nav-bar-menu` (header) and `sgs/nav-drawer-menu` (inside sgs/nav-drawer).

    <!-- wp:sgs/nav-menu {...} -->                     (top level)   -> sgs/nav-bar-menu
    <!-- wp:sgs/nav-drawer --><!-- wp:sgs/nav-menu --> (nested)      -> sgs/nav-drawer-menu

THE D542 TRIAD (`.claude/THE-MIGRATION-METHOD.md`): --survey (exhaustive census before any
design decision) -> --fix (codemod) -> --check (gate). ONE detector, three modes. No phase
does by hand what its own detector could do.

WHY A NEW SCRIPT AND NOT `migrate-core-blocks/driver.py` (verified 2026-09-14, three
disqualifiers, none of them cosmetic):
  1. Its replacement map is `source -> exactly ONE target` (`load_replaces_map` does
     `out[core] = slug`). A bar/drawer split is one source to TWO targets; the data model
     cannot express it.
  2. Its pairing hook `transform(node, text)` receives only the node and the raw text —
     no ancestor chain. It therefore cannot DECIDE the fork even if the map could hold it.
  3. `driver.py::HANDS_OFF` hard-skips `*framework-header-default.php` and
     `*header-search-*.php` — four of the nine pattern files this migration must touch,
     skipped SILENTLY (`if zone_of(rel) != 'safe': continue`).
This script instead models on `migrate-theme-attr-rename.py`: same parsing primitive
(`json.JSONDecoder().raw_decode()` on the JSON inside a `<!-- wp:sgs/* {...} -->` comment),
same refuse-rather-than-guess discipline, and NO exclusion list.

WHY THE ROUTING KEY IS NESTING, NOT AN ATTRIBUTE: every header pattern carries TWO
nav-menu instances — a bar one at top level and a drawer one inside `sgs/nav-drawer` — and
the distinction is encoded nowhere in the attributes (the drawer instance is typically a
bare `{"ref":0}`). Depth inside `sgs/nav-drawer` is the ONLY discriminator, so this script
parses real block-comment nesting rather than regex-matching opening comments alone.

⛔ GATED ON THE DESTINATION BLOCKS EXISTING. `--fix` and `--check` refuse to run until
`src/blocks/nav-bar-menu/block.json` and `src/blocks/nav-drawer-menu/block.json` are both
present. Rewriting a pattern to a block WordPress cannot resolve would render nothing and
fail the (deliberately empty) oldshape-audit baseline on the next deploy. `--survey` is
ungated by design — the census is exactly what you run BEFORE the blocks exist.

WHAT --survey REPORTS
---------------------
  SECTION A  every `sgs/nav-menu` block-comment instance, with its ancestor chain, and the
             bar/drawer routing each one would receive.
  SECTION B  every `sgs-nav-menu` / `sgs_nav_menu` / `sgs/nav-menu` LITERAL, bucketed by
             kind. The buckets exist because a naive replace of `sgs-nav-menu__` misses
             five of them — see BLIND_SPOT_KINDS.
  SECTION C  which files read each of the 156 block attributes, as the evidence base for
             the bar/drawer/both classification Step 2 needs. Reported as EVIDENCE, never
             as a verdict — a name-prefix guess is not a classification.

WHAT IT DOES NOT DO
-------------------
* Does not touch stored post_content. Live pages, `wp_template_part` 2671, `wp_block`
  reusables and revisions are a separate pass modelled on `migrate-stored-tier-scalars.py`
  (D788, proven on canary page 2742). See the plan's Step 5.
* Does not rename BEM roots, CSS, JS selectors or PHP identifiers — that is Step 3, and it
  is a different edit shape (literals in source, not JSON in block comments). This script
  only COUNTS them, so Step 3 has an authoritative denominator.
* Does not guess when a block comment's JSON will not parse — it reports the instance as
  UNPARSEABLE and leaves it alone.
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')

REPO = Path(__file__).resolve().parents[4]
BLOCKS_DIR = REPO / 'plugins' / 'sgs-blocks' / 'src' / 'blocks'

SOURCE_BLOCK = 'sgs/nav-menu'
DRAWER_BLOCK = 'sgs/nav-drawer'
TARGET_BAR = 'sgs/nav-bar-menu'
TARGET_DRAWER = 'sgs/nav-drawer-menu'

THEME_DIRS = [
    REPO / 'theme' / 'sgs-theme' / 'patterns',
    REPO / 'theme' / 'sgs-theme' / 'templates',
    REPO / 'theme' / 'sgs-theme' / 'parts',
]

# Source trees scanned for LITERALS (section B) and attribute reads (section C).
# `build/` is excluded: it is generated by `npm run build` from `src/`, so editing it is
# never correct and counting it would double every figure.
LITERAL_ROOTS = [
    REPO / 'plugins' / 'sgs-blocks' / 'src',
    REPO / 'plugins' / 'sgs-blocks' / 'includes',
    REPO / 'plugins' / 'sgs-blocks' / 'scripts',
    REPO / 'theme' / 'sgs-theme',
]
LITERAL_EXTS = {'.php', '.js', '.jsx', '.ts', '.css', '.json', '.py', '.html'}
EXCLUDE_PARTS = {'node_modules', 'build', '__pycache__', '.git', 'vendor'}

# One full block-comment token: opening, closing, or self-closing.
#   group 1 = '/' when this is a CLOSING comment
#   group 2 = namespaced block name
#   group 3 = '/' when this is SELF-CLOSING (never pushes a nesting level)
_BLOCK_TOKEN_RE = re.compile(
    r'<!--\s*(/?)wp:([a-z][a-z0-9-]*/[a-zA-Z0-9-]+)((?:(?!-->).)*?)(/?)-->',
    re.DOTALL,
)

# ── Literal buckets ────────────────────────────────────────────────────────────────────
# The five marked BLIND SPOT are invisible to a naive replace of `sgs-nav-menu__`, which is
# the obvious pattern and the one a first attempt reaches for. Each is a real breakage:
# the root-class array is STOP E25 (a cross-file detector cannot see a split literal array),
# and `.wp-block-sgs-nav-menu` is generated by WP from the slug, so hand-written selectors
# referencing it go dead SILENTLY the moment the block is renamed.
BLIND_SPOT_KINDS = {
    'root_class_literal', 'uid_prefix', 'wp_block_selector', 'keyframes_or_details_name',
    'php_identifier',
}
LITERAL_PATTERNS = [
    ('bem_element',              re.compile(r'sgs-nav-menu__[a-z0-9-]+')),
    ('root_class_literal',       re.compile(r'''['"]sgs-nav-menu['"]''')),
    ('wp_block_selector',        re.compile(r'wp-block-sgs-nav-menu\b')),
    ('keyframes_or_details_name', re.compile(r'sgs-nav-menu-(?:submenu|accordion)[a-z0-9-]*')),
    ('uid_prefix',               re.compile(r'''['"]sgs-nav-menu-['"]''')),
    ('php_identifier',           re.compile(r'\bsgs_nav_menu_[a-z_]+')),
    ('block_slug',               re.compile(r'sgs/nav-menu\b')),
]


def _skip(path: Path) -> bool:
    return any(p in EXCLUDE_PARTS for p in path.parts)


SELF = Path(__file__).resolve()


def iter_source_files():
    """Every scannable source file. Excludes THIS script: its own docstring names every
    literal it hunts for, which on the first run added 12 phantom `sgs/nav-menu` and 2
    phantom `.wp-block-sgs-nav-menu` hits to the very denominator it exists to establish."""
    for root in LITERAL_ROOTS:
        if not root.exists():
            continue
        for f in root.rglob('*'):
            if (f.is_file() and f.suffix in LITERAL_EXTS and not _skip(f)
                    and f.resolve() != SELF):
                yield f


def iter_theme_files():
    for d in THEME_DIRS:
        if not d.exists():
            continue
        for f in sorted(d.rglob('*')):
            if f.is_file() and f.suffix in {'.php', '.html'}:
                yield f


# ── Section A: block-comment instances with real nesting ───────────────────────────────

def iter_instances(text: str):
    """Walk every block comment in `text`, maintaining a real nesting stack, and yield one
    record per `sgs/nav-menu` instance.

    A hand-rolled brace matcher is NOT used for the attributes JSON: `raw_decode` consumes
    exactly one JSON value starting at the opening brace, so nested objects (`padding`,
    `gridTemplateColumns`, ...) are never mishandled. Self-closing comments never push a
    level, which is what keeps `<!-- wp:sgs/nav-menu /-->` from swallowing its siblings.

    Yields: (start, end, attrs|None, ancestors:list[str], raw_attr_span|None)
    """
    stack: list[str] = []
    for m in _BLOCK_TOKEN_RE.finditer(text):
        closing, name, middle, self_closing = m.group(1), m.group(2), m.group(3), m.group(4)

        if closing:
            # Pop to the matching ancestor. Tolerates malformed markup rather than
            # desynchronising the whole file on one stray closer.
            if name in stack:
                while stack and stack.pop() != name:
                    pass
            continue

        attrs = None
        attr_span = None
        brace = middle.find('{')
        if brace != -1:
            idx = m.start(3) + brace
            try:
                obj, end = json.JSONDecoder().raw_decode(text, idx)
                if isinstance(obj, dict):
                    attrs, attr_span = obj, (idx, end)
            except json.JSONDecodeError:
                attrs, attr_span = None, None

        if name == SOURCE_BLOCK:
            yield m.start(), m.end(), attrs, list(stack), attr_span

        if not self_closing:
            stack.append(name)


def route_for(ancestors: list[str]) -> str:
    """The ONLY routing rule: nested anywhere inside sgs/nav-drawer -> drawer block."""
    return TARGET_DRAWER if DRAWER_BLOCK in ancestors else TARGET_BAR


def survey_instances():
    rows = []
    for f in iter_theme_files():
        text = f.read_text(encoding='utf-8', errors='replace')
        for start, _end, attrs, ancestors, attr_span in iter_instances(text):
            line = text.count('\n', 0, start) + 1
            rows.append({
                'file': f,
                'line': line,
                'attrs': attrs,
                'unparseable': attrs is None and attr_span is None
                               and '{' in text[start:_end],
                'ancestors': ancestors,
                'route': route_for(ancestors),
            })
    return rows


# ── Section B: literal census ──────────────────────────────────────────────────────────

def survey_literals():
    buckets: dict[str, list] = defaultdict(list)
    for f in iter_source_files():
        try:
            text = f.read_text(encoding='utf-8', errors='replace')
        except OSError:
            continue
        if 'nav-menu' not in text and 'nav_menu' not in text:
            continue
        for kind, pat in LITERAL_PATTERNS:
            n = len(pat.findall(text))
            if n:
                buckets[kind].append((f, n))
    return buckets


def is_cross_block(f: Path) -> bool:
    """A file outside the nav-menu/nav-drawer block folders and outside the shared nav
    includes still reading nav-menu's classes — mega-panel/view.js is the known case, and
    it breaks silently if Step 3 misses it."""
    s = f.as_posix()
    if '/blocks/nav-menu/' in s or '/blocks/nav-drawer/' in s:
        return False
    if '/includes/nav-menu-' in s or 'class-sgs-nav-menu-source' in s:
        return False
    return True


def is_frozen_fixture(f: Path) -> bool:
    return 'hover-guard/test-fixtures' in f.as_posix()


# ── Section C: attribute read-sites ────────────────────────────────────────────────────

def load_source_attributes() -> list[str]:
    bj = BLOCKS_DIR / 'nav-menu' / 'block.json'
    if not bj.exists():
        return []
    data = json.loads(bj.read_text(encoding='utf-8'))
    return sorted(data.get('attributes', {}).keys())


def _is_nav_file(f: Path, text: str) -> bool:
    """Section C scans ONLY nav-related files. Without this gate the scan is worthless for
    generically-named attributes: a bare word-boundary match on `gap` hit 832 files on the
    first run, because "gap" is also an English word appearing in prose and comments across
    the whole plugin. Restricting to files that actually touch nav is what makes a count
    mean "reads this nav attribute" rather than "contains this substring"."""
    s = f.as_posix()
    if '/blocks/nav-menu/' in s or '/blocks/nav-drawer/' in s:
        return True
    if '/includes/nav-menu-' in s or 'nav-interactivity' in s or 'effects/nav-' in s:
        return True
    return ('sgs/nav-menu' in text) or ('sgs-nav-menu' in text) or ('sgs_nav_menu' in text)


def survey_attribute_reads(attrs: list[str]):
    """For each attribute, which nav files reference it. EVIDENCE for the Step 2
    classification, deliberately not a verdict: a name-prefix guess ("`burger*` is
    bar-only") is exactly the kind of inference this project's root-cause rule forbids
    acting on unproven.

    Two precision gates, both learned from the first run:
      * `_is_nav_file` — see its docstring (the `gap` = 832 files problem).
      * an IDENTIFIER context — the name must appear quoted (`'gap'`), as a property
        (`.gap`), or as a key/assignment (`gap:` / `gap =`). A bare `\\b` match still
        counts prose. Generic names (gap, ref, padding, margin) are unusable without this.
    """
    reads: dict[str, set] = {a: set() for a in attrs}
    pats = {
        a: re.compile(
            r'''['"]{}['"]'''.format(re.escape(a))          # 'gap' / "gap"
            + r'|\.' + re.escape(a) + r'\b'                  # .gap
            + r'|\b' + re.escape(a) + r'\s*[:=]'             # gap: / gap =
        )
        for a in attrs
    }
    for f in iter_source_files():
        if is_frozen_fixture(f):
            continue
        try:
            text = f.read_text(encoding='utf-8', errors='replace')
        except OSError:
            continue
        if not _is_nav_file(f, text):
            continue
        for a in attrs:
            if a in text and pats[a].search(text):
                reads[a].add(f)
    return reads


def _short(f: Path) -> str:
    try:
        return str(f.relative_to(REPO)).replace('\\', '/')
    except ValueError:
        return str(f)


# ── Gate ───────────────────────────────────────────────────────────────────────────────

def targets_exist() -> tuple[bool, list[str]]:
    missing = [
        t for t in (TARGET_BAR, TARGET_DRAWER)
        if not (BLOCKS_DIR / t.split('/', 1)[1] / 'block.json').exists()
    ]
    return (not missing), missing


# ── Reporting ──────────────────────────────────────────────────────────────────────────

def report_survey() -> int:
    print('=' * 78)
    print('SECTION A — sgs/nav-menu block-comment instances (routing by nesting)')
    print('=' * 78)
    rows = survey_instances()
    if not rows:
        print('  none found in theme patterns/templates/parts.')
    by_route = defaultdict(list)
    for r in rows:
        by_route[r['route']].append(r)
    for route in (TARGET_BAR, TARGET_DRAWER):
        group = by_route.get(route, [])
        print(f'\n  -> {route}  ({len(group)} instance(s))')
        for r in group:
            chain = ' > '.join(r['ancestors'][-2:]) or '(top level)'
            keys = ','.join(sorted(r['attrs'].keys())) if r['attrs'] else '(no attrs)'
            flag = '  ** UNPARSEABLE JSON' if r['unparseable'] else ''
            print(f'     {_short(r["file"])}:{r["line"]}')
            print(f'        in: {chain}')
            print(f'        attrs: {keys}{flag}')
    files = {r['file'] for r in rows}
    print(f'\n  TOTAL: {len(rows)} instance(s) across {len(files)} file(s) — '
          f'{len(by_route.get(TARGET_BAR, []))} bar, {len(by_route.get(TARGET_DRAWER, []))} drawer.')
    unparseable = [r for r in rows if r['unparseable']]
    if unparseable:
        print(f'  ** {len(unparseable)} instance(s) with unparseable JSON — --fix will refuse these.')

    print()
    print('=' * 78)
    print('SECTION B — literal census (the Step 3 denominator)')
    print('=' * 78)
    buckets = survey_literals()
    grand = 0
    for kind, _pat in LITERAL_PATTERNS:
        entries = buckets.get(kind, [])
        total = sum(n for _f, n in entries)
        grand += total
        blind = '  [BLIND SPOT — a naive `sgs-nav-menu__` replace MISSES this]' \
            if kind in BLIND_SPOT_KINDS else ''
        print(f'\n  {kind}: {total} occurrence(s) in {len(entries)} file(s){blind}')
        for f, n in sorted(entries, key=lambda e: -e[1]):
            marks = []
            if is_cross_block(f):
                marks.append('CROSS-BLOCK')
            if is_frozen_fixture(f):
                marks.append('FROZEN FIXTURE - regenerate, do not edit')
            suffix = ('   <- ' + ', '.join(marks)) if marks else ''
            print(f'     {n:5}  {_short(f)}{suffix}')
    print(f'\n  GRAND TOTAL: {grand} literal occurrence(s).')

    print()
    print('=' * 78)
    print('SECTION C — attribute read-sites (evidence for bar/drawer classification)')
    print('=' * 78)
    attrs = load_source_attributes()
    if not attrs:
        print('  could not read src/blocks/nav-menu/block.json — skipped.')
    else:
        reads = survey_attribute_reads(attrs)
        orphans = [a for a in attrs if not reads[a]]
        print(f'  {len(attrs)} attribute(s) declared on {SOURCE_BLOCK}.\n')
        for a in attrs:
            fs = sorted(reads[a], key=lambda p: _short(p))
            where = ', '.join(_short(f) for f in fs[:4])
            more = f' (+{len(fs) - 4} more)' if len(fs) > 4 else ''
            print(f'  {a:34} {len(fs):3} file(s)  {where}{more}')
        if orphans:
            print(f'\n  ** {len(orphans)} attribute(s) with NO read site found — '
                  f'candidates for deletion rather than migration:')
            for a in orphans:
                print(f'     {a}')
    print()
    ok, missing = targets_exist()
    if not ok:
        print(f'NOTE: --fix / --check are gated until these exist: {", ".join(missing)}')
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(
        description='Census + codemod for the sgs/nav-menu bar/drawer split.')
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument('--survey', action='store_true',
                      help='Exhaustive read-only census (default).')
    mode.add_argument('--fix', action='store_true',
                      help='Rewrite theme pattern instances. Dry-run unless --apply.')
    mode.add_argument('--check', action='store_true',
                      help='Gate: non-zero exit while any sgs/nav-menu instance remains.')
    ap.add_argument('--apply', action='store_true', help='With --fix, actually write.')
    args = ap.parse_args()

    if args.fix or args.check:
        ok, missing = targets_exist()
        if not ok:
            print('[nav-menu-split] REFUSED — destination block(s) not present: '
                  f'{", ".join(missing)}.')
            print('  Scaffold them first (plan Step 2). Rewriting a pattern to a block '
                  'WordPress cannot resolve renders nothing and fails the oldshape gate.')
            return 1
        print('[nav-menu-split] --fix/--check are not implemented yet (plan Step 4). '
              'The destination blocks now exist, so this gate has been cleared.')
        return 1

    return report_survey()


if __name__ == '__main__':
    sys.exit(main())
