"""check_css_property_reseed.py — Check #8: css_property/css_layer reseed-survival.

Spec ref: Spec 31 FR-31-5.2/5.3 (D281) — the declarative CSS-property column.

The `block_attributes.css_property` / `css_layer` / `css_element` / `css_state` /
`css_tier` columns are DERIVED — /sgs-update rebuilds block_attributes every run, then
`_apply_attr_classification_overrides` re-writes them from TWO reseed-durable channels
(2026-07-21 architecture, Bean-approved — mirrors the existing box_family pattern):

  1. The DERIVED layer — `behavioural-analyser/css-property-classifications.json`,
     regenerated by extract-signatures.py's classifier. Applied FIRST.
  2. The OVERRIDE layer — `attr-classification-overrides.json`
     (ATTR_CLASSIFICATION_OVERRIDES). Applied AFTER, wins on any field conflict.

Both are legitimate, reseed-durable sources; a bare SQLite UPDATE outside either channel
is the ONLY thing that gets wiped on the next reseed (STOP-24).

This is the "reseed diff test for the corrected subset" (council must-fix #5). It proves
three invariants against the LIVE seeded DB — cheap, no /sgs-update run needed (if the
seeder is idempotent, the DB always equals the two channels' declarations):

  A. EVERY css_property override in ATTR_CLASSIFICATION_OVERRIDES is reflected in the DB
     row (slug, attr) with matching css_property + css_layer. A mismatch means the
     correction did NOT survive the reseed (or a bare UPDATE was used) — fail.
  B. NO DB row carries a non-NULL css_property that is NOT declared in EITHER channel
     (the derived layer OR the override layer) — proves no rogue seeding outside the two
     legitimate channels, and that undeclared attrs stay NULL (parity-neutral by
     construction: they never enter the column-first path).
  C. NO (block, css_property, css_layer, css_element, css_state, css_tier) resolves to
     >=2 attrs — the runtime AmbiguousLayerAttrError guard, caught at gate time before it
     can fire mid-clone. Widened 2026-07-21 to include the new element/state/tier
     discriminators: this makes the previously-flagged 106 "collisions" (columnsDesktop
     vs columnsTablet vs columnsMobile on the same css_property; linkColour vs
     linkHoverColour differing by state; nameColour vs textColour differing by element)
     genuinely non-colliding, because they differ on at least one axis of the full key —
     NOT suppression: two attrs identical on css_property AND element AND state AND tier
     AND layer still violate, because they would still genuinely contend for the same
     routing slot at clone time.

Empty result before any css_property is seeded (columns absent → nothing to check) and
after (the seeded subset matches). Wired into db-consistency/run.py (STOP-6).
"""
from __future__ import annotations

import importlib.util
import sqlite3
import sys
from pathlib import Path
from typing import Any

sys.stdout.reconfigure(encoding="utf-8")

from .models import Violation, css_property_reseed_key

# Load ATTR_CLASSIFICATION_OVERRIDES from sgs-update-v2.py (the reseed-durable source of
# truth). Same importlib pattern as resolver_bridge — import the REAL constant so this
# check can never drift from the seeder (R-22-1). FAIL LOUD if unavailable.
_SEEDER_PATH = Path(__file__).resolve().parents[1] / "sgs-update-v2.py"

if not _SEEDER_PATH.exists():
    raise ImportError(
        f"[check_css_property_reseed] Cannot find sgs-update-v2.py at {_SEEDER_PATH}.\n"
        "This check imports ATTR_CLASSIFICATION_OVERRIDES to verify the DB against the "
        "reseed-durable source (R-22-1)."
    )

_spec = importlib.util.spec_from_file_location("sgs_update_v2_seeder", str(_SEEDER_PATH))
_seeder_mod: Any = importlib.util.module_from_spec(_spec)  # type: ignore[arg-type]
try:
    _spec.loader.exec_module(_seeder_mod)  # type: ignore[union-attr]
except Exception as exc:  # noqa: BLE001
    raise ImportError(
        f"[check_css_property_reseed] Failed to load sgs-update-v2.py: {exc}"
    ) from exc

if not hasattr(_seeder_mod, "ATTR_CLASSIFICATION_OVERRIDES"):
    raise ImportError(
        "[check_css_property_reseed] sgs-update-v2.py has no ATTR_CLASSIFICATION_OVERRIDES "
        "symbol — cannot verify the css_property seeding (R-22-1)."
    )

ATTR_CLASSIFICATION_OVERRIDES: dict = _seeder_mod.ATTR_CLASSIFICATION_OVERRIDES

# Reuse the REAL seeder function for the derived (classifier) layer too — same
# anti-drift rationale as importing ATTR_CLASSIFICATION_OVERRIDES above (R-22-1):
# this check must never hand-roll a second reader of css-property-classifications.json
# that could silently diverge from what the seeder actually applies.
if not hasattr(_seeder_mod, "_load_css_property_classifications"):
    raise ImportError(
        "[check_css_property_reseed] sgs-update-v2.py has no "
        "_load_css_property_classifications symbol — cannot verify the derived-layer "
        "channel (R-22-1)."
    )
_load_css_property_classifications = _seeder_mod._load_css_property_classifications


def _legitimate_sources() -> dict[tuple[str, str], dict[str, object]]:
    """Return {(block_slug, attr): fields} for EVERY (slug, attr) declared in either
    reseed-durable channel — the derived layer (base) merged with the override layer
    (wins on conflict), exactly mirroring `_apply_attr_classification_overrides`'s own
    merge order in sgs-update-v2.py. Used by Check B: a DB row is "rogue" only if it
    is NOT explainable by this combined source, i.e. by neither channel."""
    combined: dict[tuple[str, str], dict[str, object]] = {
        k: dict(v) for k, v in _load_css_property_classifications().items()
    }
    for key, fields in ATTR_CLASSIFICATION_OVERRIDES.items():
        combined.setdefault(key, {}).update(fields)
    return combined


def _expected_declarations() -> dict[tuple[str, str], tuple[str, "str | None"]]:
    """Return {(block_slug, attr): (css_property, css_layer)} for every override that
    declares a css_property. css_layer defaults to None (self/OUTER) when unset."""
    out: dict[tuple[str, str], tuple[str, str | None]] = {}
    for (slug, attr), fields in ATTR_CLASSIFICATION_OVERRIDES.items():
        if not isinstance(fields, dict) or "css_property" not in fields:
            continue
        out[(slug, attr)] = (fields.get("css_property"), fields.get("css_layer"))
    return out


def _columns_present(conn: sqlite3.Connection) -> bool:
    cols = {r[1] for r in conn.execute("PRAGMA table_info(block_attributes)").fetchall()}
    return "css_property" in cols and "css_layer" in cols


def run(conn: sqlite3.Connection) -> list[Violation]:
    """Run check #8 against the live DB connection."""
    violations: list[Violation] = []
    expected = _expected_declarations()

    if not _columns_present(conn):
        # Columns not yet materialised (no css_property override reseeded). Nothing to
        # check — but if the override map DECLARES corrections, that IS a violation
        # (the seeder never ran / the column was dropped).
        if expected:
            for (slug, attr) in sorted(expected):
                violations.append(Violation(
                    check="css_property_reseed",
                    block=slug,
                    detail=(
                        f"{slug}.{attr}: ATTR_CLASSIFICATION_OVERRIDES declares css_property "
                        f"but block_attributes has no css_property column — the seeder has "
                        f"not applied the corrections."
                    ),
                    fix="Run python plugins/sgs-blocks/scripts/sgs-update-v2.py --stage 1 to seed the css_property/css_layer columns.",
                    key=css_property_reseed_key(slug, attr, "no-column"),
                ))
        return violations

    # A. every declared override is reflected in the DB.
    for (slug, attr), (exp_prop, exp_layer) in sorted(expected.items()):
        row = conn.execute(
            "SELECT css_property, css_layer FROM block_attributes "
            "WHERE block_slug = ? AND attr_name = ?",
            (slug, attr),
        ).fetchone()
        if row is None:
            violations.append(Violation(
                check="css_property_reseed",
                block=slug,
                detail=f"{slug}.{attr}: declared in ATTR_CLASSIFICATION_OVERRIDES but no such block_attributes row.",
                fix=f"Fix the (slug, attr) key for {slug}.{attr} in ATTR_CLASSIFICATION_OVERRIDES, or add the attr to the block.",
                key=css_property_reseed_key(slug, attr, "missing-row"),
            ))
            continue
        db_prop, db_layer = row
        if db_prop != exp_prop or db_layer != exp_layer:
            violations.append(Violation(
                check="css_property_reseed",
                block=slug,
                detail=(
                    f"{slug}.{attr}: css_property/css_layer did NOT survive reseed — "
                    f"DB has ({db_prop!r}, {db_layer!r}), override declares ({exp_prop!r}, {exp_layer!r}). "
                    f"A bare SQLite UPDATE is wiped every reseed (STOP-24)."
                ),
                fix="Declare the correction in ATTR_CLASSIFICATION_OVERRIDES + run sgs-update-v2.py --stage 1 (never a bare UPDATE).",
                key=css_property_reseed_key(slug, attr, "mismatch"),
            ))

    # B. no rogue non-NULL css_property outside EITHER reseed-durable channel (derived
    # layer OR override layer — 2026-07-21 two-layer architecture).
    legitimate = _legitimate_sources()
    db_declared = conn.execute(
        "SELECT block_slug, attr_name, css_property, css_layer FROM block_attributes "
        "WHERE css_property IS NOT NULL"
    ).fetchall()
    for slug, attr, db_prop, _db_layer in db_declared:
        if (slug, attr) not in legitimate:
            violations.append(Violation(
                check="css_property_reseed",
                block=slug,
                detail=(
                    f"{slug}.{attr}: has css_property={db_prop!r} in the DB but is NOT declared in "
                    f"either the derived classifier layer (css-property-classifications.json) or "
                    f"ATTR_CLASSIFICATION_OVERRIDES — a rogue seed (would vanish on the next reseed)."
                ),
                fix=(
                    f"Either re-run extract-signatures.py so the classifier declares "
                    f"{slug}.{attr}, add it to ATTR_CLASSIFICATION_OVERRIDES, or remove "
                    f"the stray css_property."
                ),
                key=css_property_reseed_key(slug, attr, "rogue"),
            ))

    # C. no (block, css_property, css_layer, css_element, css_state, css_tier) resolves
    # to >=2 attrs (runtime-ambiguity guard). Widened 2026-07-21 to include the new
    # discriminators — an attr differing by element/state/tier is NOT the same routing
    # slot (columnsDesktop vs columnsTablet, tabTextColour vs tabHoverBgColour, etc.);
    # only a genuine full-key collision still violates.
    ambiguous = conn.execute(
        "SELECT block_slug, css_property, "
        "IFNULL(css_layer, ''), IFNULL(css_element, ''), IFNULL(css_state, ''), IFNULL(css_tier, ''), "
        "COUNT(*), GROUP_CONCAT(attr_name) "
        "FROM block_attributes WHERE css_property IS NOT NULL "
        "GROUP BY block_slug, css_property, IFNULL(css_layer, ''), IFNULL(css_element, ''), "
        "IFNULL(css_state, ''), IFNULL(css_tier, '') HAVING COUNT(*) > 1"
    ).fetchall()
    for slug, prop, layer, element, state, tier, n, attrs in ambiguous:
        key_desc = (
            f"property={prop}, layer={layer or 'NULL'}, element={element or 'NULL'}, "
            f"state={state or 'NULL'}, tier={tier or 'NULL'}"
        )
        violations.append(Violation(
            check="css_property_reseed",
            block=slug,
            detail=(
                f"{slug}: ({key_desc}) declares {n} attrs [{attrs}] — the "
                f"column-first resolver raises AmbiguousLayerAttrError on this at clone time. "
                f"These attrs are identical on EVERY routing axis (property/layer/element/"
                f"state/tier), so they genuinely contend for the same slot."
            ),
            fix=f"Only one attr may own ({slug}, {key_desc}) — remove the duplicate declaration, "
                f"or add a distinguishing css_element/css_state/css_tier if they legitimately differ.",
            key=css_property_reseed_key(slug, f"{prop}:{layer}:{element}:{state}:{tier}", "ambiguous"),
        ))

    # D. undeclared sub-element paint (2026-07-23, Bean — "protect CSS from being dropped
    # or misrouted"). An attr whose css_property is one that ALWAYS lands on a specific
    # painted element (colour / border-colour / border-radius / box-shadow / object-fit)
    # but which resolved css_element IS NULL *and* derived_selector IS NULL is an
    # UNDECLARED sub-element paint: the seeder's emission parser could not trace the
    # `.block__child` selector (a $var / implode() indirection in render.php it can't
    # follow) AND the block's block.json manifest does not declare the element — so the
    # attr fell into the ROOT routing domain and would misroute (or land nowhere) on a
    # clone. This is distinct from a legitimate root-scoped NULL (width/padding delivered
    # via a root custom-property, e.g. brand-strip.fadeWidth / icon.backgroundPadding):
    # those properties are NOT in the painted-on-a-specific-element set below, so they
    # never trip this. Fix = declare the element in the block's own
    # `supports.sgs.elements.<el>.attrMap` (the R-31-1 declarative source, NOT an
    # attr-classification override), or unify a mode-exclusive duplicate (the way
    # sgs/separator's contentColour merged contentIconColour + contentTextColour). Then
    # reseed. Root cause + mechanism: extract-signatures.py::_load_element_manifest_reverse.
    _PAINTED_ON_ELEMENT_PROPS = (
        "color",
        "border-color",
        "border-top-color",
        "border-right-color",
        "border-bottom-color",
        "border-left-color",
        "border-radius",
        "box-shadow",
        "object-fit",
    )
    _painted_placeholders = ",".join("?" for _ in _PAINTED_ON_ELEMENT_PROPS)
    undeclared = conn.execute(
        "SELECT block_slug, attr_name, css_property FROM block_attributes "
        "WHERE css_element IS NULL AND derived_selector IS NULL AND css_state IS NULL "
        f"AND css_property IN ({_painted_placeholders})",
        _PAINTED_ON_ELEMENT_PROPS,
    ).fetchall()
    for slug, attr, prop in undeclared:
        child = slug.split("/")[-1]
        violations.append(Violation(
            check="css_property_reseed",
            block=slug,
            detail=(
                f"{slug}.{attr}: paints css_property={prop!r} (a property that always lands on a "
                f"specific element) but resolved css_element=NULL AND derived_selector=NULL — an "
                f"UNDECLARED sub-element paint. The seeder could not trace the .{child}__<child> "
                f"selector and the manifest does not declare the element, so it fell to the root "
                f"routing domain and would misroute on a clone."
            ),
            fix=(
                f"Declare the element in {slug}'s block.json supports.sgs.elements.<el>.attrMap "
                f'(add "css:{prop}": "{attr}"), NOT an attr-classification override; or unify a '
                f"mode-exclusive duplicate. Then run /sgs-update. See extract-signatures.py."
            ),
            key=css_property_reseed_key(slug, attr, "undeclared-subelement"),
        ))

    return violations
