<?php
/**
 * REST API endpoints for form submission and uploads.
 *
 * Registers two public endpoints:
 * - POST /sgs-forms/v1/submit — process form submission
 * - POST /sgs-forms/v1/upload — handle file upload
 *
 * @package SGS\Blocks\Forms
 *
 * @since 1.0.0
 */

namespace SGS\Blocks\Forms;

defined( 'ABSPATH' ) || exit;

class Form_REST_API {

	/**
	 * Register REST API routes.
	 *
	 * @since 1.0.0
	 */
	public static function register(): void {
		add_action( 'rest_api_init', [ __CLASS__, 'register_routes' ] );
	}

	/**
	 * Register form submission and upload routes.
	 *
	 * @since 1.0.0
	 */
	public static function register_routes(): void {
		// Form submission endpoint.
		register_rest_route(
			'sgs-forms/v1',
			'/submit',
			[
				'methods'             => 'POST',
				'callback'            => [ __CLASS__, 'handle_submit' ],
				'permission_callback' => [ __CLASS__, 'verify_form_nonce' ],
				'args'                => [
					'formId'   => [
						'required'          => true,
						'type'              => 'string',
						'sanitize_callback' => 'sanitize_key',
					],
					'fields'   => [
						'required'          => true,
						'type'              => 'object',
						'validate_callback' => function ( $value ) {
							if ( strlen( wp_json_encode( $value ) ) > 65536 ) {
								return new \WP_Error( 'fields_too_large', __( 'Form data exceeds maximum size.', 'sgs-blocks' ) );
							}
							foreach ( $value as $v ) {
								if ( is_object( $v ) ) {
									return new \WP_Error( 'fields_invalid', __( 'Field values must be text or arrays.', 'sgs-blocks' ) );
								}
							}
							return true;
						},
					],
					'fileIds'  => [
						'required' => false,
						'type'     => 'array',
						'default'  => [],
						'items'    => [
							'type' => 'integer',
						],
					],
					'honeypot' => [
						'required'          => false,
						'type'              => 'string',
						'default'           => '',
						'sanitize_callback' => 'sanitize_text_field',
					],
					'storeSubmissions' => [
						'required' => false,
						'type'     => 'boolean',
						'default'  => true,
					],
					'turnstileResponse' => [
						'required'          => false,
						'type'              => 'string',
						'default'           => '',
						'sanitize_callback' => 'sanitize_text_field',
					],
					'notificationEmail' => [
						'required'          => false,
						'type'              => 'string',
						'default'           => '',
						'sanitize_callback' => 'sanitize_email',
					],
				],
			]
		);

		// File upload endpoint.
		register_rest_route(
			'sgs-forms/v1',
			'/upload',
			[
				'methods'             => 'POST',
				'callback'            => [ __CLASS__, 'handle_upload' ],
				'permission_callback' => [ __CLASS__, 'verify_form_nonce' ],
			]
		);

		// Admin: list submissions with optional filtering.
		register_rest_route(
			'sgs-forms/v1',
			'/submissions',
			[
				'methods'             => 'GET',
				'callback'            => [ __CLASS__, 'list_submissions' ],
				'permission_callback' => [ __CLASS__, 'require_manage_options' ],
				'args'                => [
					'form_id' => [
						'required'          => false,
						'type'              => 'string',
						'sanitize_callback' => 'sanitize_key',
					],
					'status' => [
						'required'          => false,
						'type'              => 'string',
						'sanitize_callback' => 'sanitize_key',
					],
					'per_page' => [
						'required' => false,
						'type'     => 'integer',
						'default'  => 20,
						'minimum'  => 1,
						'maximum'  => 100,
					],
					'page' => [
						'required' => false,
						'type'     => 'integer',
						'default'  => 1,
						'minimum'  => 1,
					],
				],
			]
		);

		// Admin: single submission detail.
		register_rest_route(
			'sgs-forms/v1',
			'/submissions/(?P<id>[\d]+)',
			[
				[
					'methods'             => 'GET',
					'callback'            => [ __CLASS__, 'get_submission' ],
					'permission_callback' => [ __CLASS__, 'require_manage_options' ],
				],
				[
					'methods'             => 'DELETE',
					'callback'            => [ __CLASS__, 'delete_submission' ],
					'permission_callback' => [ __CLASS__, 'require_manage_options' ],
				],
			]
		);

		// Admin: CSV export for a specific form.
		register_rest_route(
			'sgs-forms/v1',
			'/export/(?P<formId>[a-z0-9\-_]+)',
			[
				'methods'             => 'GET',
				'callback'            => [ __CLASS__, 'export_submissions' ],
				'permission_callback' => [ __CLASS__, 'require_manage_options' ],
			]
		);
	}

	/**
	 * Permission callback: verify the wp_rest nonce for CSRF protection.
	 *
	 * Public forms accept anonymous submissions, but every request must carry
	 * a valid nonce generated by render.php to prove it originates from the site.
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return true|\WP_Error True if nonce is valid, WP_Error otherwise.
	 */
	public static function verify_form_nonce( \WP_REST_Request $request ) {
		$nonce = $request->get_header( 'x_wp_nonce' );

		if ( ! $nonce || ! wp_verify_nonce( $nonce, 'wp_rest' ) ) {
			return new \WP_Error(
				'rest_forbidden',
				__( 'Invalid security token. Please refresh the page and try again.', 'sgs-blocks' ),
				[ 'status' => 403 ]
			);
		}

		return true;
	}

	/**
	 * Permission callback: require manage_options capability (admin endpoints).
	 *
	 * @since 1.0.0
	 * @return true|\WP_Error True if user can manage options, WP_Error otherwise.
	 */
	public static function require_manage_options(): bool|\WP_Error {
		if ( current_user_can( 'manage_options' ) ) {
			return true;
		}

		return new \WP_Error(
			'rest_forbidden',
			__( 'You do not have permission to access form submissions.', 'sgs-blocks' ),
			[ 'status' => 403 ]
		);
	}

	/**
	 * List form submissions with optional filtering.
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response Response with submissions array and pagination data.
	 */
	public static function list_submissions( \WP_REST_Request $request ): \WP_REST_Response {
		global $wpdb;

		$table_name = $wpdb->prefix . 'sgs_form_submissions';
		$form_id    = $request->get_param( 'form_id' );
		$status     = $request->get_param( 'status' );
		$per_page   = $request->get_param( 'per_page' );
		$page       = $request->get_param( 'page' );
		$offset     = ( $page - 1 ) * $per_page;

		// Build WHERE clause.
		$where        = 'WHERE 1=1';
		$prepare_args = [];

		if ( ! empty( $form_id ) ) {
			$where         .= ' AND form_id = %s';
			$prepare_args[] = $form_id;
		}

		if ( ! empty( $status ) ) {
			$where         .= ' AND status = %s';
			$prepare_args[] = $status;
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$total = $wpdb->get_var(
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$wpdb->prepare( "SELECT COUNT(*) FROM $table_name $where", ...$prepare_args )
		);

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$rows = $wpdb->get_results(
			// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$wpdb->prepare(
				"SELECT id, form_id, files, payment_status, payment_amount, ip_address, user_id, status, created_at FROM $table_name $where ORDER BY created_at DESC LIMIT %d OFFSET %d",
				...array_merge( $prepare_args, [ $per_page, $offset ] )
			)
		);

		$response = new \WP_REST_Response(
			[
				'submissions' => $rows,
				'total'       => (int) $total,
				'pages'       => (int) ceil( $total / $per_page ),
				'page'        => $page,
			],
			200
		);

		$response->header( 'X-WP-Total', (int) $total );
		$response->header( 'X-WP-TotalPages', (int) ceil( $total / $per_page ) );

		return $response;
	}

	/**
	 * Get a single submission by ID.
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response|\WP_Error Submission data or 404.
	 */
	public static function get_submission( \WP_REST_Request $request ): \WP_REST_Response|\WP_Error {
		global $wpdb;

		$table_name    = $wpdb->prefix . 'sgs_form_submissions';
		$submission_id = absint( $request->get_param( 'id' ) );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$row = $wpdb->get_row(
			$wpdb->prepare( "SELECT * FROM $table_name WHERE id = %d", $submission_id )
		);

		if ( ! $row ) {
			return new \WP_Error(
				'not_found',
				__( 'Submission not found.', 'sgs-blocks' ),
				[ 'status' => 404 ]
			);
		}

		// Decode JSON columns.
		$row->data  = json_decode( $row->data, true );
		$row->files = $row->files ? json_decode( $row->files, true ) : [];

		return new \WP_REST_Response( $row, 200 );
	}

	/**
	 * Delete a submission (GDPR erasure).
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response|\WP_Error Success response or 404.
	 */
	public static function delete_submission( \WP_REST_Request $request ): \WP_REST_Response|\WP_Error {
		global $wpdb;

		$table_name    = $wpdb->prefix . 'sgs_form_submissions';
		$submission_id = absint( $request->get_param( 'id' ) );

		// Check submission exists.
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$exists = $wpdb->get_var(
			$wpdb->prepare( "SELECT id FROM $table_name WHERE id = %d", $submission_id )
		);

		if ( ! $exists ) {
			return new \WP_Error(
				'not_found',
				__( 'Submission not found.', 'sgs-blocks' ),
				[ 'status' => 404 ]
			);
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		$deleted = $wpdb->delete( $table_name, [ 'id' => $submission_id ], [ '%d' ] );

		if ( false === $deleted ) {
			return new \WP_Error(
				'delete_failed',
				__( 'Failed to delete submission.', 'sgs-blocks' )
			);
		}

		return new \WP_REST_Response( [ 'deleted' => true, 'id' => $submission_id ], 200 );
	}

	/**
	 * Export all submissions for a given form as CSV.
	 *
	 * Streams CSV directly so large data sets don't exhaust PHP memory.
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return void Outputs CSV and exits.
	 */
	public static function export_submissions( \WP_REST_Request $request ): void {
		global $wpdb;

		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'Permission denied.', 'sgs-blocks' ), 403 );
		}

		$table_name = $wpdb->prefix . 'sgs_form_submissions';
		$form_id    = sanitize_key( $request->get_param( 'formId' ) );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$rows = $wpdb->get_results(
			$wpdb->prepare(
				"SELECT * FROM $table_name WHERE form_id = %s ORDER BY created_at ASC",
				$form_id
			),
			ARRAY_A
		);

		// Set CSV response headers.
		header( 'Content-Type: text/csv; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename="sgs-form-' . sanitize_file_name( $form_id ) . '-' . gmdate( 'Y-m-d' ) . '.csv"' );
		header( 'Pragma: no-cache' );
		header( 'Expires: 0' );

		$output = fopen( 'php://output', 'w' );

		if ( empty( $rows ) ) {
			fputcsv( $output, [ __( 'No submissions found.', 'sgs-blocks' ) ] );
			fclose( $output );
			exit;
		}

		// Build unified column list from all submissions' JSON data.
		$field_keys = [];
		foreach ( $rows as $row ) {
			$data = json_decode( $row['data'], true );
			if ( is_array( $data ) ) {
				foreach ( array_keys( $data ) as $key ) {
					if ( ! in_array( $key, $field_keys, true ) ) {
						$field_keys[] = $key;
					}
				}
			}
		}

		// CSV header row: metadata columns then dynamic field columns.
		$meta_cols = [ 'id', 'form_id', 'status', 'payment_status', 'payment_amount', 'ip_address', 'user_id', 'created_at' ];
		fputcsv( $output, array_merge( $meta_cols, $field_keys ) );

		// Data rows.
		foreach ( $rows as $row ) {
			$data = json_decode( $row['data'], true );
			$csv_row = [];

			foreach ( $meta_cols as $col ) {
				$csv_row[] = $row[ $col ] ?? '';
			}

			foreach ( $field_keys as $key ) {
				$val = $data[ $key ] ?? '';
				// Flatten arrays (e.g. checkboxes) to comma-separated strings.
				if ( is_array( $val ) ) {
					$val = implode( ', ', $val );
				}
				$csv_row[] = $val;
			}

			fputcsv( $output, $csv_row );
		}

		fclose( $output );
		exit;
	}

	/**
	 * Handle form submission request.
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response|\WP_Error Response with submission ID or error.
	 */
	public static function handle_submit( \WP_REST_Request $request ) {
		$form_id            = $request->get_param( 'formId' );
		$fields             = $request->get_param( 'fields' );
		$file_ids           = $request->get_param( 'fileIds' );
		$honeypot           = $request->get_param( 'honeypot' );
		$store_submissions  = $request->get_param( 'storeSubmissions' );
		$turnstile_response = $request->get_param( 'turnstileResponse' );
		$notification_email = $request->get_param( 'notificationEmail' );

		// Check honeypot (bot trap).
		if ( ! empty( $honeypot ) ) {
			// Return fake success — don't reveal the trap to automated tools.
			return new \WP_REST_Response(
				[
					'success' => true,
					'message' => __( 'Form submitted successfully.', 'sgs-blocks' ),
				],
				200
			);
		}

		// Retrieve cached form configuration (set by render.php, lives 24 hours).
		$form_config       = get_transient( 'sgs_form_config_' . sanitize_key( $form_id ) );
		$require_login     = is_array( $form_config ) ? (bool) ( $form_config['requireLogin'] ?? false ) : false;
		$rate_limit_max    = is_array( $form_config ) ? absint( $form_config['rateLimit'] ?? 5 ) : 5;
		$turnstile_enabled = is_array( $form_config ) ? (bool) ( $form_config['turnstileEnabled'] ?? false ) : false;
		$field_rules       = is_array( $form_config ) ? ( $form_config['fieldRules'] ?? [] ) : [];

		// Use notification email from cached config (server-side truth) if available,
		// falling back to the request param for backwards compatibility.
		$cached_notification_email = is_array( $form_config ) ? ( $form_config['notificationEmail'] ?? '' ) : '';
		if ( ! empty( $cached_notification_email ) ) {
			$notification_email = sanitize_email( $cached_notification_email );
		}

		// Enforce login requirement when the form editor has enabled it.
		if ( $require_login && ! is_user_logged_in() ) {
			return new \WP_Error(
				'login_required',
				__( 'You must be logged in to submit this form.', 'sgs-blocks' ),
				[ 'status' => 401 ]
			);
		}

		// Verify Cloudflare Turnstile token when CAPTCHA is enabled for this form.
		if ( $turnstile_enabled ) {
			$turnstile_result = self::verify_turnstile( $turnstile_response );
			if ( is_wp_error( $turnstile_result ) ) {
				return $turnstile_result;
			}
		}

		// Rate limiting: configurable per-form, defaulting to 5 per IP per hour.
		$rate_limit_check = self::check_rate_limit( $form_id, $rate_limit_max );

		if ( is_wp_error( $rate_limit_check ) ) {
			return $rate_limit_check;
		}

		// Server-side field validation against rules cached from render.php.
		if ( ! empty( $field_rules ) ) {
			$validation_errors = self::validate_fields( $fields, $field_rules );
			if ( ! empty( $validation_errors ) ) {
				return new \WP_Error(
					'validation_failed',
					__( 'Please correct the highlighted fields.', 'sgs-blocks' ),
					[
						'status' => 422,
						'errors' => $validation_errors,
					]
				);
			}
		}

		// Process the submission.
		$result = Form_Processor::process( $form_id, $fields, $file_ids, $store_submissions );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		// Send notification email (belt-and-suspenders: always send when configured,
		// regardless of webhook success/failure).
		if ( ! empty( $notification_email ) ) {
			self::send_notification_email( $notification_email, $form_id, $fields );
		}

		return new \WP_REST_Response(
			[
				'success'       => true,
				'message'       => __( 'Form submitted successfully.', 'sgs-blocks' ),
				'submissionId'  => $result['submission_id'],
			],
			200
		);
	}

	/**
	 * Verify a Cloudflare Turnstile token via the siteverify API.
	 *
	 * @since 1.0.0
	 * @param string $token The cf-turnstile-response token from the client.
	 * @return true|\WP_Error True on success, WP_Error on failure.
	 */
	private static function verify_turnstile( string $token ) {
		if ( empty( $token ) ) {
			return new \WP_Error(
				'turnstile_missing',
				__( 'CAPTCHA verification is required. Please complete the challenge.', 'sgs-blocks' ),
				[ 'status' => 400 ]
			);
		}

		$secret_key = get_option( 'sgs_turnstile_secret_key', '' );

		if ( empty( $secret_key ) ) {
			// Secret key not configured — skip verification gracefully.
			return true;
		}

		$response = wp_remote_post(
			'https://challenges.cloudflare.com/turnstile/v0/siteverify',
			[
				'body'    => [
					'secret'   => $secret_key,
					'response' => $token,
					'remoteip' => self::get_client_ip(),
				],
				'timeout' => 10,
			]
		);

		if ( is_wp_error( $response ) ) {
			// Network error — fail open to avoid blocking legitimate users.
			return true;
		}

		$body = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( empty( $body['success'] ) ) {
			return new \WP_Error(
				'turnstile_failed',
				__( 'CAPTCHA verification failed. Please try again.', 'sgs-blocks' ),
				[ 'status' => 403 ]
			);
		}

		return true;
	}

	/**
	 * Validate submitted fields against cached validation rules.
	 *
	 * @since 1.0.0
	 * @param array $fields     Submitted field values (key => value).
	 * @param array $field_rules Validation rules keyed by fieldName.
	 * @return array Associative array of fieldName => error message. Empty if valid.
	 */
	private static function validate_fields( array $fields, array $field_rules ): array {
		$errors = [];

		foreach ( $field_rules as $field_name => $rules ) {
			$value       = $fields[ $field_name ] ?? '';
			$label       = $rules['label'] ?? $field_name;
			$custom_err  = ! empty( $rules['customError'] ) ? $rules['customError'] : null;
			$min_length  = absint( $rules['minLength'] ?? 0 );
			$max_length  = absint( $rules['maxLength'] ?? 0 );
			$pattern     = $rules['pattern'] ?? '';
			$required    = ! empty( $rules['required'] );

			// Flatten arrays (checkboxes, tiles) to a comma-separated string for length checks.
			$str_value = is_array( $value ) ? implode( ', ', $value ) : (string) $value;

			// Required check.
			if ( $required && '' === trim( $str_value ) ) {
				/* translators: %s: Field label. */
				$errors[ $field_name ] = $custom_err ?? sprintf( __( '%s is required.', 'sgs-blocks' ), $label );
				continue;
			}

			// Skip further validation for empty optional fields.
			if ( '' === trim( $str_value ) ) {
				continue;
			}

			// Minimum length.
			if ( $min_length > 0 && mb_strlen( $str_value ) < $min_length ) {
				/* translators: 1: Field label, 2: Minimum length. */
				$errors[ $field_name ] = $custom_err ?? sprintf( __( '%1$s must be at least %2$d characters.', 'sgs-blocks' ), $label, $min_length );
				continue;
			}

			// Maximum length.
			if ( $max_length > 0 && mb_strlen( $str_value ) > $max_length ) {
				/* translators: 1: Field label, 2: Maximum length. */
				$errors[ $field_name ] = $custom_err ?? sprintf( __( '%1$s must not exceed %2$d characters.', 'sgs-blocks' ), $label, $max_length );
				continue;
			}

			// Pattern validation (regex).
			if ( ! empty( $pattern ) ) {
				// Wrap the pattern as a full regex with anchors.
				$regex = '/^(?:' . $pattern . ')$/u';
				// phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- testing if pattern is valid.
				if ( false === @preg_match( $regex, $str_value ) ) {
					// Invalid pattern — skip silently.
				} elseif ( ! preg_match( $regex, $str_value ) ) {
					/* translators: %s: Field label. */
					$errors[ $field_name ] = $custom_err ?? sprintf( __( '%s does not match the required format.', 'sgs-blocks' ), $label );
				}
			}
		}

		return $errors;
	}

	/**
	 * Send a wp_mail() notification with form submission data.
	 *
	 * Formats all submitted fields as a simple HTML table for readability.
	 * Sent regardless of webhook success/failure (belt-and-suspenders).
	 *
	 * @since 1.0.0
	 * @param string $to      Recipient email address.
	 * @param string $form_id Form identifier.
	 * @param array  $fields  Sanitised field data.
	 */
	private static function send_notification_email( string $to, string $form_id, array $fields ): void {
		if ( ! is_email( $to ) ) {
			return;
		}

		$site_name = get_bloginfo( 'name' );

		/* translators: 1: Site name, 2: Form ID. */
		$subject = sprintf( __( '[%1$s] New form submission: %2$s', 'sgs-blocks' ), $site_name, $form_id );

		// Build HTML table of field values.
		$rows = '';
		foreach ( $fields as $key => $value ) {
			$display_value = is_array( $value ) ? implode( ', ', array_map( 'sanitize_text_field', $value ) ) : sanitize_text_field( (string) $value );
			$rows .= sprintf(
				'<tr><th style="text-align:left;padding:6px 12px;background:#f5f5f5;border:1px solid #ddd;">%s</th><td style="padding:6px 12px;border:1px solid #ddd;">%s</td></tr>',
				esc_html( ucwords( str_replace( [ '_', '-' ], ' ', $key ) ) ),
				esc_html( $display_value )
			);
		}

		$message = sprintf(
			'<!DOCTYPE html><html><body style="font-family:sans-serif;color:#333;">
			<h2 style="color:#1a1a1a;">%s</h2>
			<p><strong>%s</strong> %s</p>
			<p><strong>%s</strong> %s</p>
			<table style="border-collapse:collapse;width:100%%;max-width:600px;">%s</table>
			<p style="margin-top:24px;font-size:12px;color:#999;">%s</p>
			</body></html>',
			esc_html__( 'New Form Submission', 'sgs-blocks' ),
			esc_html__( 'Form:', 'sgs-blocks' ),
			esc_html( $form_id ),
			esc_html__( 'Submitted:', 'sgs-blocks' ),
			esc_html( gmdate( 'Y-m-d H:i:s T' ) ),
			$rows,
			esc_html( sprintf(
				/* translators: %s: Site URL. */
				__( 'Submitted via %s', 'sgs-blocks' ),
				get_site_url()
			) )
		);

		$headers = [
			'Content-Type: text/html; charset=UTF-8',
			'From: ' . $site_name . ' <' . get_option( 'admin_email' ) . '>',
		];

		wp_mail( $to, $subject, $message, $headers );
	}

	/**
	 * Handle file upload request.
	 *
	 * @since 1.0.0
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response|\WP_Error Upload result or error.
	 */
	public static function handle_upload( \WP_REST_Request $request ) {
		// Rate limiting: 10 uploads per IP per hour.
		$rate_limit_check = self::check_rate_limit( 'upload' );

		if ( is_wp_error( $rate_limit_check ) ) {
			return $rate_limit_check;
		}

		$result = Form_Upload::handle( $request );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return new \WP_REST_Response( $result, 200 );
	}

	/**
	 * Check rate limit for form actions.
	 *
	 * Submissions: 5 per IP per form per hour.
	 * Uploads: 10 per IP per hour.
	 *
	 * @since 1.0.0
	 * @param string $form_id Form identifier (or 'upload' for file uploads).
	 * @param int    $max     Maximum allowed actions (default 5).
	 * @return true|\WP_Error True if allowed, WP_Error if rate limit exceeded.
	 */
	private static function check_rate_limit( string $form_id, int $max = 5 ) {
		$ip = self::get_client_ip();

		// Upload endpoint uses a higher limit.
		if ( 'upload' === $form_id ) {
			$max = 10;
		}

		// Generate transient key (MD5 to avoid special chars).
		$transient_key = 'sgs_form_rate_' . md5( $ip . $form_id );

		// Get current action count.
		$count = get_transient( $transient_key );

		if ( false === $count ) {
			// First action in this hour.
			set_transient( $transient_key, 1, HOUR_IN_SECONDS );
			return true;
		}

		if ( $count >= $max ) {
			return new \WP_Error(
				'rate_limit_exceeded',
				__( 'Too many submissions. Please try again later.', 'sgs-blocks' ),
				[ 'status' => 429 ]
			);
		}

		// Increment counter.
		set_transient( $transient_key, $count + 1, HOUR_IN_SECONDS );

		return true;
	}

	/**
	 * Get client IP address.
	 *
	 * Uses REMOTE_ADDR only — X-Forwarded-For is trivially spoofable and
	 * would let an attacker bypass rate limiting by rotating header values.
	 *
	 * @since 1.0.0
	 * @return string Validated client IP address, or 0.0.0.0 if unavailable.
	 */
	private static function get_client_ip(): string {
		$ip = ! empty( $_SERVER['REMOTE_ADDR'] )
			? sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) )
			: '';

		$ip = filter_var( $ip, FILTER_VALIDATE_IP );

		return $ip ?: '0.0.0.0';
	}
}
