<?php
/**
 * REST API endpoints for form submission and uploads.
 *
 * Registers two public endpoints:
 * - POST /sgs-forms/v1/submit — process form submission
 * - POST /sgs-forms/v1/upload — handle file upload
 *
 * @package SGS\Blocks\Forms
 */

namespace SGS\Blocks\Forms;

defined( 'ABSPATH' ) || exit;

class Form_REST_API {

	/**
	 * Register REST API routes.
	 */
	public static function register(): void {
		add_action( 'rest_api_init', [ __CLASS__, 'register_routes' ] );
	}

	/**
	 * Register form submission and upload routes.
	 */
	public static function register_routes(): void {
		// Form submission endpoint.
		register_rest_route(
			'sgs-forms/v1',
			'/submit',
			[
				'methods'             => 'POST',
				'callback'            => [ __CLASS__, 'handle_submit' ],
				'permission_callback' => [ __CLASS__, 'verify_form_nonce' ],
				'args'                => [
					'formId'   => [
						'required'          => true,
						'type'              => 'string',
						'sanitize_callback' => 'sanitize_key',
					],
					'fields'   => [
						'required'          => true,
						'type'              => 'object',
						'validate_callback' => function ( $value ) {
							if ( strlen( wp_json_encode( $value ) ) > 65536 ) {
								return new \WP_Error( 'fields_too_large', __( 'Form data exceeds maximum size.', 'sgs-blocks' ) );
							}
							foreach ( $value as $v ) {
								if ( is_object( $v ) ) {
									return new \WP_Error( 'fields_invalid', __( 'Field values must be text or arrays.', 'sgs-blocks' ) );
								}
							}
							return true;
						},
					],
					'fileIds'  => [
						'required' => false,
						'type'     => 'array',
						'default'  => [],
						'items'    => [
							'type' => 'integer',
						],
					],
					'honeypot' => [
						'required'          => false,
						'type'              => 'string',
						'default'           => '',
						'sanitize_callback' => 'sanitize_text_field',
					],
					'storeSubmissions' => [
						'required' => false,
						'type'     => 'boolean',
						'default'  => true,
					],
				],
			]
		);

		// File upload endpoint.
		register_rest_route(
			'sgs-forms/v1',
			'/upload',
			[
				'methods'             => 'POST',
				'callback'            => [ __CLASS__, 'handle_upload' ],
				'permission_callback' => [ __CLASS__, 'verify_form_nonce' ],
			]
		);
	}

	/**
	 * Permission callback: verify the wp_rest nonce for CSRF protection.
	 *
	 * Public forms accept anonymous submissions, but every request must carry
	 * a valid nonce generated by render.php to prove it originates from the site.
	 *
	 * @param \WP_REST_Request $request REST API request.
	 * @return true|\WP_Error True if nonce is valid, WP_Error otherwise.
	 */
	public static function verify_form_nonce( \WP_REST_Request $request ) {
		$nonce = $request->get_header( 'x_wp_nonce' );

		if ( ! $nonce || ! wp_verify_nonce( $nonce, 'wp_rest' ) ) {
			return new \WP_Error(
				'rest_forbidden',
				__( 'Invalid security token. Please refresh the page and try again.', 'sgs-blocks' ),
				[ 'status' => 403 ]
			);
		}

		return true;
	}

	/**
	 * Handle form submission request.
	 *
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response|\WP_Error Response with submission ID or error.
	 */
	public static function handle_submit( \WP_REST_Request $request ) {
		$form_id           = $request->get_param( 'formId' );
		$fields            = $request->get_param( 'fields' );
		$file_ids          = $request->get_param( 'fileIds' );
		$honeypot          = $request->get_param( 'honeypot' );
		$store_submissions = $request->get_param( 'storeSubmissions' );

		// Check honeypot (bot trap).
		if ( ! empty( $honeypot ) ) {
			// Return fake success — don't reveal the trap.
			return new \WP_REST_Response(
				[
					'success' => true,
					'message' => __( 'Form submitted successfully.', 'sgs-blocks' ),
				],
				200
			);
		}

		// Rate limiting: 5 submissions per IP per hour.
		$rate_limit_check = self::check_rate_limit( $form_id );

		if ( is_wp_error( $rate_limit_check ) ) {
			return $rate_limit_check;
		}

		// Process the submission.
		$result = Form_Processor::process( $form_id, $fields, $file_ids, $store_submissions );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return new \WP_REST_Response(
			[
				'success'       => true,
				'message'       => __( 'Form submitted successfully.', 'sgs-blocks' ),
				'submissionId'  => $result['submission_id'],
			],
			200
		);
	}

	/**
	 * Handle file upload request.
	 *
	 * @param \WP_REST_Request $request REST API request.
	 * @return \WP_REST_Response|\WP_Error Upload result or error.
	 */
	public static function handle_upload( \WP_REST_Request $request ) {
		// Rate limiting: 10 uploads per IP per hour.
		$rate_limit_check = self::check_rate_limit( 'upload' );

		if ( is_wp_error( $rate_limit_check ) ) {
			return $rate_limit_check;
		}

		$result = Form_Upload::handle( $request );

		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return new \WP_REST_Response( $result, 200 );
	}

	/**
	 * Check rate limit for form actions.
	 *
	 * Submissions: 5 per IP per form per hour.
	 * Uploads: 10 per IP per hour.
	 *
	 * @param string $form_id Form identifier (or 'upload' for file uploads).
	 * @param int    $max     Maximum allowed actions (default 5).
	 * @return true|\WP_Error True if allowed, WP_Error if rate limit exceeded.
	 */
	private static function check_rate_limit( string $form_id, int $max = 5 ) {
		$ip = self::get_client_ip();

		// Upload endpoint uses a higher limit.
		if ( 'upload' === $form_id ) {
			$max = 10;
		}

		// Generate transient key (MD5 to avoid special chars).
		$transient_key = 'sgs_form_rate_' . md5( $ip . $form_id );

		// Get current action count.
		$count = get_transient( $transient_key );

		if ( false === $count ) {
			// First action in this hour.
			set_transient( $transient_key, 1, HOUR_IN_SECONDS );
			return true;
		}

		if ( $count >= $max ) {
			return new \WP_Error(
				'rate_limit_exceeded',
				__( 'Too many submissions. Please try again later.', 'sgs-blocks' ),
				[ 'status' => 429 ]
			);
		}

		// Increment counter.
		set_transient( $transient_key, $count + 1, HOUR_IN_SECONDS );

		return true;
	}

	/**
	 * Get client IP address.
	 *
	 * Uses REMOTE_ADDR only — X-Forwarded-For is trivially spoofable and
	 * would let an attacker bypass rate limiting by rotating header values.
	 *
	 * @return string Validated client IP address, or 0.0.0.0 if unavailable.
	 */
	private static function get_client_ip(): string {
		$ip = ! empty( $_SERVER['REMOTE_ADDR'] )
			? sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) )
			: '';

		$ip = filter_var( $ip, FILTER_VALIDATE_IP );

		return $ip ?: '0.0.0.0';
	}
}
