<?php
/**
 * Handle file uploads for form fields.
 *
 * Validates file size and MIME type, then moves the file into a
 * PRIVATE, non-web-servable directory (never the public uploads
 * folder — see `resolve_private_dir()`) under a random, unguessable
 * filename, and creates a private attachment post. Returns the
 * attachment ID for later reference; callers must never expose a
 * direct URL to the stored file — downloads go through
 * `Form_Download` (admin-post.php, capability + nonce gated).
 *
 * @package SGS\Blocks\Forms
 */

namespace SGS\Blocks\Forms;

defined( 'ABSPATH' ) || exit;

/**
 * Handle file uploads for form fields.
 */
class Form_Upload {

	/**
	 * Post meta key marking an attachment as an SGS form upload.
	 *
	 * `Form_Download::handle_download()` requires this meta before it
	 * will stream a file, so this endpoint can never be turned into a
	 * generic "download any attachment by ID" oracle.
	 */
	const UPLOAD_META_KEY = '_sgs_form_upload';

	/**
	 * Option key holding the random directory-name suffix used for the
	 * fallback in-uploads private folder (`sgs-private-<suffix>`).
	 *
	 * Generated once per site and reused so every SGS form upload lands
	 * in the same private folder, rather than a fresh unguessable name
	 * (and a fresh `.htaccess`/`index.php` pair) per file.
	 */
	const DIR_SUFFIX_OPTION = 'sgs_form_private_dir_suffix';

	/**
	 * Handle file upload from REST request.
	 *
	 * @param \WP_REST_Request $request REST API request object.
	 * @return array|\WP_Error Upload result with id, name, size — or error.
	 *                         Never includes a URL: the stored file is
	 *                         not web-servable.
	 */
	public static function handle( \WP_REST_Request $request ) {
		$files = $request->get_file_params();

		if ( empty( $files['file'] ) ) {
			return new \WP_Error( 'no_file', __( 'No file was uploaded.', 'sgs-blocks' ) );
		}

		$file = $files['file'];

		// Validate file size.
		$max_size = self::get_max_upload_size();

		if ( $file['size'] > $max_size ) {
			return new \WP_Error(
				'file_too_large',
				sprintf(
					/* translators: %s: maximum file size in MB */
					__( 'File size exceeds maximum allowed (%s MB).', 'sgs-blocks' ),
					size_format( $max_size )
				)
			);
		}

		// Validate MIME type.
		$allowed_types = self::get_allowed_mime_types();
		$file_type     = wp_check_filetype_and_ext( $file['tmp_name'], $file['name'] );

		if ( empty( $file_type['type'] ) || ! in_array( $file_type['type'], $allowed_types, true ) ) {
			return new \WP_Error(
				'invalid_file_type',
				__( 'File type is not allowed.', 'sgs-blocks' )
			);
		}

		// Redirect wp_handle_upload() into the private directory for the
		// duration of this single call, and force a random filename so the
		// original name never appears in a path. Reusing wp_handle_upload()
		// keeps its own safety checks (is_uploaded_file, extension re-check,
		// upload_max_filesize handling) rather than reimplementing them.
		$private_dir = self::resolve_private_dir();

		if ( is_wp_error( $private_dir ) ) {
			return $private_dir;
		}

		$filter = static function ( $dirs ) use ( $private_dir ) {
			$dirs['path']   = $private_dir['path'];
			$dirs['url']    = $private_dir['path']; // Never dereferenced as a public URL; see class docblock.
			$dirs['subdir'] = '';
			$dirs['basedir'] = $private_dir['path'];
			$dirs['baseurl'] = $private_dir['path'];
			return $dirs;
		};

		// wp_handle_upload() lives in an admin include that a front-end REST
		// request never loads (WP-CLI and wp-admin do, which hides this).
		require_once ABSPATH . 'wp-admin/includes/file.php';

		add_filter( 'upload_dir', $filter );

		$upload = wp_handle_upload(
			$file,
			[
				'test_form'               => false,
				'unique_filename_callback' => [ __CLASS__, 'random_filename' ],
			]
		);

		remove_filter( 'upload_dir', $filter );

		if ( isset( $upload['error'] ) ) {
			return new \WP_Error( 'upload_failed', $upload['error'] );
		}

		// Original client filename, kept only for admin display (post_title
		// and later use in the Content-Disposition header) — the file on
		// disk uses the random name generated by random_filename().
		$original_name = sanitize_file_name( $file['name'] );

		// Create attachment post (private so it's not publicly listed).
		$attachment_id = wp_insert_attachment(
			[
				'post_mime_type' => $upload['type'],
				'post_title'     => $original_name,
				'post_content'   => '',
				'post_status'    => 'private',
			],
			$upload['file']
		);

		if ( is_wp_error( $attachment_id ) ) {
			return $attachment_id;
		}

		update_post_meta( $attachment_id, self::UPLOAD_META_KEY, 1 );

		// Generate attachment metadata under the same upload_dir filter, with
		// NO derived copies: no intermediate sizes and no "-scaled" big-image
		// copy. A form upload is only ever downloaded whole by an admin, and
		// every extra copy of a (possibly health-data) image is one more file
		// the privacy eraser would have to find and delete.
		require_once ABSPATH . 'wp-admin/includes/image.php';
		add_filter( 'upload_dir', $filter );
		add_filter( 'intermediate_image_sizes_advanced', '__return_empty_array', 999 );
		add_filter( 'big_image_size_threshold', '__return_false', 999 );
		$attach_data = wp_generate_attachment_metadata( $attachment_id, $upload['file'] );
		remove_filter( 'big_image_size_threshold', '__return_false', 999 );
		remove_filter( 'intermediate_image_sizes_advanced', '__return_empty_array', 999 );
		remove_filter( 'upload_dir', $filter );
		wp_update_attachment_metadata( $attachment_id, $attach_data );

		return [
			'id'   => $attachment_id,
			'name' => $original_name,
			'size' => filesize( $upload['file'] ),
		];
	}

	/**
	 * Unique_filename_callback for wp_handle_upload(): ignore the client's
	 * original name entirely and generate a random one, preserving only
	 * the (already type-checked) extension.
	 *
	 * @param string $dir  Directory the file will be moved into (unused).
	 * @param string $name Original sanitised filename (unused — the point
	 *                     is to never derive the stored name from it).
	 * @param string $ext  File extension, including the leading dot.
	 * @return string Random filename with the original extension.
	 */
	public static function random_filename( $dir, $name, $ext ): string {
		return bin2hex( random_bytes( 16 ) ) . $ext;
	}

	/**
	 * Resolve the private, non-web-servable directory that form uploads
	 * are stored in.
	 *
	 * Prefers a directory one level ABOVE `ABSPATH` (i.e. outside the web
	 * root entirely — the only option that also protects against nginx,
	 * which does not honour `.htaccess`). Falls back to
	 * `wp-content/uploads/sgs-private-<random>/` with a deny-all
	 * `.htaccess` + empty `index.php` when the outside-webroot directory
	 * is not writable (a common restriction on shared hosting).
	 *
	 * The chosen path is cached in a site option so every upload — and
	 * every later download — resolves to the same directory.
	 *
	 * @return array|\WP_Error {
	 *     @type string $path     Absolute filesystem path, trailing slash.
	 *     @type bool   $outside_webroot Whether the outside-webroot directory was used.
	 * } or WP_Error if neither location is writable.
	 */
	public static function resolve_private_dir() {
		// 1. Try outside the web root.
		$outside = trailingslashit( dirname( ABSPATH ) ) . 'sgs-private-uploads/';

		if ( wp_mkdir_p( $outside ) && wp_is_writable( $outside ) ) {
			return [
				'path'             => $outside,
				'outside_webroot'  => true,
			];
		}

		// 2. Fall back to a randomly-named, access-denied folder inside
		// wp-content/uploads/. The random suffix means the folder name
		// itself is not guessable even though it sits under the public
		// uploads tree; .htaccess (Apache/LiteSpeed) denies all requests.
		$suffix = get_option( self::DIR_SUFFIX_OPTION );

		if ( ! $suffix || ! is_string( $suffix ) ) {
			$suffix = bin2hex( random_bytes( 12 ) );
			update_option( self::DIR_SUFFIX_OPTION, $suffix, false );
		}

		$upload_dir = wp_upload_dir();
		$fallback   = trailingslashit( $upload_dir['basedir'] ) . 'sgs-private-' . $suffix . '/';

		if ( ! wp_mkdir_p( $fallback ) || ! wp_is_writable( $fallback ) ) {
			return new \WP_Error(
				'private_dir_unwritable',
				__( 'Could not create a private storage location for uploads.', 'sgs-blocks' )
			);
		}

		self::ensure_deny_all_guards( $fallback );

		return [
			'path'            => $fallback,
			'outside_webroot' => false,
		];
	}

	/**
	 * Write a deny-all `.htaccess` and an empty `index.php` into the
	 * fallback private directory, if not already present.
	 *
	 * Defence in depth for Apache/LiteSpeed hosts (LiteSpeed — the
	 * Hostinger stack this framework deploys to — honours `.htaccess`);
	 * nginx does not read `.htaccess` at all, which is why the
	 * outside-webroot location in resolve_private_dir() is preferred
	 * wherever the host allows it.
	 *
	 * @param string $dir Directory to guard, trailing slash.
	 */
	private static function ensure_deny_all_guards( string $dir ): void {
		$htaccess = $dir . '.htaccess';

		if ( ! file_exists( $htaccess ) ) {
			// Covers both the legacy Apache 2.2 directive and the 2.4+
			// equivalent, since we don't know the target server's version.
			file_put_contents(
				$htaccess,
				"Order deny,allow\nDeny from all\n\nRequire all denied\n"
			);
		}

		$index = $dir . 'index.php';

		if ( ! file_exists( $index ) ) {
			file_put_contents( $index, "<?php\n// Silence is golden.\n" );
		}
	}

	/**
	 * Get maximum upload size in bytes.
	 *
	 * @return int Maximum upload size (default 10MB).
	 */
	private static function get_max_upload_size(): int {
		/**
		 * Filter the maximum file upload size for forms.
		 *
		 * @param int $max_size Maximum size in bytes (default 10485760 = 10MB).
		 */
		return apply_filters( 'sgs_form_max_upload_size', 10 * 1024 * 1024 );
	}

	/**
	 * Get allowed MIME types for uploads.
	 *
	 * @return array Allowed MIME types.
	 */
	private static function get_allowed_mime_types(): array {
		/**
		 * Filter allowed MIME types for form uploads.
		 *
		 * @param array $mime_types Allowed MIME types.
		 */
		return apply_filters(
			'sgs_form_allowed_mime_types',
			[
				'image/jpeg',
				'image/png',
				'image/gif',
				'image/webp',
				'application/pdf',
			]
		);
	}
}
