#!/usr/bin/env python3
"""register_patterns.py -- Spec 15 Phase 6 Step 0 +REGISTER tail.

After a successful clone run, walk the stage-9 artefact and register every
novel pattern surfaced:

    1. Write PHP pattern file at theme/sgs-theme/patterns/<slug>.php with
       header comment + body containing the composed block markup
       (theme reads via register_block_pattern())
    2. INSERT a row into sgs-framework.db patterns table
    3. INSERT a row into uimax-pro-max.db patterns table with Rosetta Stone
       equivalent_implementations payload (sgs_block + html_css fallback)

Idempotent at three gates: (a) PHP file existence check before write,
(b) sgs-db SELECT-then-INSERT pattern in `_insert_sgs_pattern`,
(c) uimax SELECT-then-INSERT pattern in `_insert_uimax_pattern`. The
canonical uimax patterns table has NO UNIQUE constraint on `slug`, so
the explicit pre-check is the only correct guard against duplicate rows.

Module-only -- no CLI. Called from sgs-clone-orchestrator.py after
orchestrator_main.run() returns outcome.overall == 'success'.

UK English in comments + output.
"""
from __future__ import annotations

import json
import re
import sqlite3
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

REPO = Path(__file__).resolve().parents[4]
PATTERNS_DIR = REPO / "theme" / "sgs-theme" / "patterns"
SGS_DB = Path.home() / ".claude" / "skills" / "sgs-wp-engine" / "sgs-framework.db"
UIMAX_DB = Path.home() / ".agents" / "skills" / "ui-ux-pro-max" / "scripts" / "ui-ux-pro-max.db"

_SLUG_RE = re.compile(r"^[a-z][a-z0-9-]*$")


@dataclass
class PatternRegistration:
    slug: str
    title: str
    section_class: str
    blocks_used: list[str] = field(default_factory=list)
    php_path: str = ""
    sgs_db_inserted: bool = False
    uimax_inserted: bool = False
    skipped_reason: str = ""


@dataclass
class RegisterResult:
    run_id: str
    registered: list[PatternRegistration] = field(default_factory=list)
    skipped: list[PatternRegistration] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    @property
    def registered_count(self) -> int:
        return len(self.registered)

    @property
    def skipped_count(self) -> int:
        return len(self.skipped)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _humanise_title(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").title()


def _section_class_to_slug(section_class: str) -> str:
    """Map 'sgs-featured-product' or 'featured-product' to a pattern slug.

    Prefix-strip is case-insensitive so SGS-Header / sgs-Header / sgs-header
    all resolve to 'header'. Output is always lowercase + hyphen-only per
    Spec 15 §8.1 slug regex (lowercase plus hyphen).
    """
    s = section_class.strip()
    if s.lower().startswith("sgs-"):
        s = s[4:]
    return s.lower()


def _composed_inner_blocks(block_markup: str) -> list[str]:
    """Extract registered block names used inside the composed markup."""
    return sorted(set(re.findall(r"<!-- wp:([a-z0-9/_-]+)", block_markup)))


def _emit_php(slug: str, title: str, category: str, description: str,
              block_markup: str, source_run_id: str) -> str:
    """Render the PHP pattern file body."""
    sluggified = slug.lower().strip()
    if not _SLUG_RE.match(sluggified):
        raise ValueError(f"invalid pattern slug {sluggified!r}")
    # Strip the title's surrounding quotes if present, escape for PHP comment block
    safe_title = title.replace("*/", "* /")
    safe_desc = description.replace("*/", "* /")
    header = (
        "<?php\n"
        "/**\n"
        f" * Title: {safe_title}\n"
        f" * Slug: sgs/{sluggified}\n"
        f" * Categories: {category}\n"
        f" * Description: {safe_desc}\n"
        " *\n"
        " * Auto-generated by sgs-clone pipeline +REGISTER tail.\n"
        f" * Source clone run: {source_run_id}\n"
        f" * Generated: {_now_iso()}\n"
        " * Edits to this file may be overwritten on the next clone run --\n"
        " * author the source mockup instead.\n"
        " *\n"
        " * @package SGS\\Theme\n"
        " */\n"
        "?>\n\n"
    )
    return header + block_markup.rstrip() + "\n"


def _section_results_with_composed_pattern(extract_artefact: dict) -> list[dict]:
    """Filter the per-section extract results to those the pipeline composed.

    A "novel pattern" candidate is any per-section result whose status is
    `deferred-composed-pattern` (matched to core/group, fell through to the
    composer in stage 4). Already-known composite blocks (sgs/hero etc.)
    skip the pattern-registration path -- they ARE the pattern.
    """
    out = (extract_artefact or {}).get("output") or extract_artefact or {}
    results = out.get("per_section_results") or []
    return [r for r in results if r.get("status") == "deferred-composed-pattern"
            and r.get("block_markup")]


def _insert_sgs_pattern(slug: str, title: str, description: str,
                       blocks_used: list[str], file_path: str,
                       category: str = "sgs",
                       block_composition: list[str] | None = None,
                       db_path: Path = SGS_DB) -> bool:
    """INSERT OR IGNORE into sgs-framework.db patterns. Returns True on insert."""
    if not db_path.exists():
        return False
    con = sqlite3.connect(str(db_path), timeout=10.0)
    try:
        cur = con.execute(
            "SELECT 1 FROM patterns WHERE slug = ?",
            (f"sgs/{slug}",),
        )
        if cur.fetchone():
            return False
        con.execute(
            """INSERT INTO patterns
                 (slug, title, category, description, blocks_used, file_path,
                  is_auto_generated, source, block_composition, created_at)
               VALUES (?, ?, ?, ?, ?, ?, 1, 'sgs-clone-pipeline', ?, ?)""",
            (
                f"sgs/{slug}",
                title,
                category,
                description,
                ",".join(blocks_used),
                file_path,
                json.dumps(block_composition or blocks_used, ensure_ascii=False),
                _now_iso(),
            ),
        )
        con.commit()
        return True
    finally:
        con.close()


def _insert_uimax_pattern(slug: str, title: str, blocks_used: list[str],
                          section_class: str,
                          db_path: Path = UIMAX_DB) -> bool:
    """INSERT into uimax patterns with Rosetta Stone equivalent_implementations.

    Returns True on insert. Soft-fail: DB unavailable or table missing
    returns False without raising -- uimax is the catalogue layer, not a
    runtime gate.
    """
    if not db_path.exists():
        return False
    try:
        con = sqlite3.connect(str(db_path), timeout=10.0)
    except sqlite3.Error:
        return False
    try:
        # Verify the patterns table exists in uimax
        has_table = con.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='patterns'"
        ).fetchone()
        if not has_table:
            return False
        # Belt-and-braces existence check: the canonical uimax patterns table
        # has no UNIQUE constraint on slug, so ON CONFLICT can't catch a
        # duplicate. Pre-check ensures we never write the same slug twice.
        existing = con.execute(
            "SELECT 1 FROM patterns WHERE slug = ?", (f"sgs/{slug}",)
        ).fetchone()
        if existing:
            return False
        cols = [r[1] for r in con.execute("PRAGMA table_info(patterns)").fetchall()]
        # Build a payload using only columns the uimax patterns table actually has;
        # always include slug + title. Add equivalent_implementations / source /
        # is_canonical_for_sgs_drafts if those columns exist.
        payload: dict = {
            "slug": f"sgs/{slug}",
            "title": title,
            "category": "sgs",
            "description": f"Auto-registered from sgs-clone of .{section_class}",
        }
        equivalents = {
            "sgs_block": ",".join(blocks_used) if blocks_used else None,
            "html_css": section_class,
        }
        if "equivalent_implementations" in cols:
            payload["equivalent_implementations"] = json.dumps(equivalents, ensure_ascii=False)
        if "source" in cols:
            payload["source"] = "sgs-clone-pipeline"
        if "is_canonical_for_sgs_drafts" in cols:
            payload["is_canonical_for_sgs_drafts"] = 1
        if "primary_class" in cols:
            payload["primary_class"] = f".sgs-{slug}"
        # Filter payload to columns that exist in the actual table
        usable = {k: v for k, v in payload.items() if k in cols}
        if not usable:
            return False
        col_list = ", ".join(usable.keys())
        placeholders = ", ".join("?" for _ in usable)
        # ON CONFLICT DO NOTHING - slug should be unique or have an index;
        # if the table lacks a unique constraint we fall back to a manual
        # exists check.
        try:
            con.execute(
                f"INSERT INTO patterns ({col_list}) VALUES ({placeholders}) "
                "ON CONFLICT DO NOTHING",
                tuple(usable.values()),
            )
            con.commit()
            return con.total_changes > 0
        except sqlite3.OperationalError:
            existing = con.execute(
                "SELECT 1 FROM patterns WHERE slug = ?", (f"sgs/{slug}",)
            ).fetchone()
            if existing:
                return False
            con.execute(
                f"INSERT INTO patterns ({col_list}) VALUES ({placeholders})",
                tuple(usable.values()),
            )
            con.commit()
            return True
    finally:
        con.close()


def register_run(
    run_id: str,
    extract_artefact: dict,
    boundary_artefact: dict | None = None,
    patterns_dir: Path = PATTERNS_DIR,
    sgs_db: Path = SGS_DB,
    uimax_db: Path = UIMAX_DB,
) -> RegisterResult:
    """Register every novel pattern produced by a successful clone run.

    Args:
      run_id: the clone-pipeline run identifier (used for traceability)
      extract_artefact: the stage-4 dict (output.per_section_results carries
        the composed-pattern entries that need registration)
      boundary_artefact: the stage-1 dict (used to enrich pattern metadata
        with the original class signature where available)
      patterns_dir: where the PHP files land (default theme/sgs-theme/patterns/)
      sgs_db / uimax_db: catalogue paths (defaults to canonical locations)
    """
    result = RegisterResult(run_id=run_id)
    boundary_by_id: dict[str, dict] = {}
    if boundary_artefact:
        for b in boundary_artefact.get("boundaries", []):
            boundary_by_id[b.get("boundary_id", "")] = b

    composed = _section_results_with_composed_pattern(extract_artefact)
    if not composed:
        return result

    patterns_dir.mkdir(parents=True, exist_ok=True)

    for entry in composed:
        section_id = entry.get("section_id") or ""
        boundary_id = entry.get("boundary_id") or ""
        section_class = section_id or boundary_id
        slug = _section_class_to_slug(section_class)

        reg = PatternRegistration(
            slug=slug,
            title=_humanise_title(slug),
            section_class=section_class,
            blocks_used=_composed_inner_blocks(entry.get("block_markup") or ""),
        )

        if not _SLUG_RE.match(slug):
            reg.skipped_reason = f"invalid pattern slug derived: {slug!r}"
            result.skipped.append(reg)
            continue

        php_path = patterns_dir / f"{slug}.php"
        if php_path.exists():
            reg.skipped_reason = "PHP pattern file already exists -- preserved"
            result.skipped.append(reg)
            continue

        description = (
            f"Auto-registered from the .{section_class} section of a clone run. "
            f"Inner blocks: {', '.join(reg.blocks_used)}."
        )

        try:
            php_body = _emit_php(
                slug=slug,
                title=reg.title,
                category="sgs",
                description=description,
                block_markup=entry["block_markup"],
                source_run_id=run_id,
            )
            php_path.write_text(php_body, encoding="utf-8")
            resolved_php = php_path.resolve()
            try:
                reg.php_path = str(resolved_php.relative_to(REPO))
            except ValueError:
                # patterns_dir lives outside the repo (test fixture path).
                # Fall back to the absolute path; sgs-db stores file_path
                # verbatim and a callable test treats both forms equally.
                reg.php_path = str(resolved_php)
        except (OSError, ValueError) as exc:
            result.errors.append(f"PHP write failed for {slug}: {exc}")
            reg.skipped_reason = f"PHP write failed: {exc}"
            result.skipped.append(reg)
            continue

        try:
            reg.sgs_db_inserted = _insert_sgs_pattern(
                slug=slug,
                title=reg.title,
                description=description,
                blocks_used=reg.blocks_used,
                file_path=reg.php_path,
                block_composition=reg.blocks_used,
                db_path=sgs_db,
            )
        except sqlite3.Error as exc:
            result.errors.append(f"sgs-db insert failed for {slug}: {exc}")

        try:
            reg.uimax_inserted = _insert_uimax_pattern(
                slug=slug,
                title=reg.title,
                blocks_used=reg.blocks_used,
                section_class=section_class,
                db_path=uimax_db,
            )
        except sqlite3.Error as exc:
            result.errors.append(f"uimax insert failed for {slug}: {exc}")

        result.registered.append(reg)

    return result


def summarise(result: RegisterResult) -> str:
    """Plain-text summary for stdout."""
    lines = [
        f"[+REGISTER] run_id={result.run_id} "
        f"registered={result.registered_count} skipped={result.skipped_count}"
    ]
    for r in result.registered:
        lines.append(
            f"  + sgs/{r.slug}  blocks={','.join(r.blocks_used)}  "
            f"php={r.php_path}  sgs_db={'+' if r.sgs_db_inserted else 'skip'}  "
            f"uimax={'+' if r.uimax_inserted else 'skip'}"
        )
    for r in result.skipped:
        lines.append(f"  - sgs/{r.slug}  skipped: {r.skipped_reason}")
    for err in result.errors:
        lines.append(f"  ! {err}")
    return "\n".join(lines)
