import sqlite3
c=sqlite3.connect('file:C:/Users/Bean/.claude/skills/sgs-wp-engine/sgs-framework.db?mode=ro',uri=True)
qs={
'render_rep':"select block_slug,role,role_order,source_file from block_render_repeaters order by random() limit 3",
'render_rep_blocks':"select count(distinct block_slug) from block_render_repeaters",
'render_single':"select block_slug,role,role_order,source_file from block_render_singletons order by random() limit 3",
'render_single_blocks':"select count(distinct block_slug) from block_render_singletons",
'render_comp':"select block_slug,child_slug,call_order,source_file from block_render_composition limit 3",
'composition':"select block_slug,composition_role,accepts_allowed_blocks,container_kind from block_composition where accepts_allowed_blocks is not null limit 3",
'cap_func':"select block_slug,capability from block_capabilities where kind='functional' order by random() limit 5",
'cap_funcvocab':"select capability,count(*) from block_capabilities where kind='functional' group by 1",
'selectors':"select block_slug,element,selector from block_selectors order by random() limit 3",
'supports_sgs':"select support_name,count(*) from block_supports where source='sgs' group by 1 order by 2 desc limit 25",
'supports_sample':"select block_slug,support_name,substr(support_value,1,150) from block_supports where source='sgs' and support_name like 'sgs%' order by random() limit 4",
'preset':"select * from preset_implications limit 4",
'variant_slots':"select block_slug,variant_value,unique_slot from variant_slots order by random() limit 4",
'variant_attr':"select slug,variant_attr from blocks where variant_attr is not null",
'slots':"select slot_name,scope,aliases,standalone_block from slots order by random() limit 3",
'propsuf':"select suffix,role,css_property,is_token_matched,token_source,kind_override from property_suffixes order by random() limit 4",
'modsuf':"select * from modifier_suffixes limit 5",
'design_tokens':"select token_type,count(*) from design_tokens group by 1",
'dt_sample':"select slug,token_type,default_value from design_tokens order by random() limit 3",
'markup':"select validation_status,is_hand_authored,source,count(*) from markup_examples group by 1,2,3",
'markup_blocks':"select count(distinct block_slug) from markup_examples where block_slug like 'sgs/%'",
'motion':"select preset_slug,tier,animated_property,direction,magnitude_min,magnitude_max,duration_ms,easing_curve from motion_shape_signatures limit 3",
'lrs':"select library_name,signal_type,aliases from library_runtime_signals",
'excluded':"select css_property,reason from excluded_properties",
'html_tag':"select html_tag,core_block_slug from html_tag_to_core_block limit 5",
'style_var':"select slug,client,source_path,is_active from style_variations",
'gotchas':"select title,component from gotchas limit 4",
'patterns':"select slug,blocks_used,file_path from patterns where blocks_used is not null limit 2",
'theme_parts':"select name,part_type,file_path from theme_parts limit 3",
'hooks':"select source,count(*) from hooks group by 1",
'docs':"select source,doc_type,count(*) from docs group by 1,2 order by 3 desc limit 8",
'fx':"select effect,tier,requires,triggers,scope from fx_effects limit 3",
'arr':"select block_slug,array_attr,field_key,role from array_item_schema order by random() limit 4",
'arr_blocks':"select count(distinct block_slug),count(distinct block_slug||array_attr) from array_item_schema",
'indexed':"select source,count(*), min(last_indexed), max(last_indexed) from indexed_files group by 1",
'pattern_cov':"select status,count(*) from pattern_coverage group by 1",
'roles_sample':"select role_name,classification,substr(description,1,80) from roles order by random() limit 3",
'meta':"select * from schema_metadata",
'blocks_stale':"select max(updated_at),min(updated_at) from blocks where source='sgs'",
}
for k,q in qs.items():
    try: print(k, c.execute(q).fetchall())
    except Exception as e: print(k,'ERR',e)
