// The walker config Fill generates (FR-47-4 step 4): one pair per skeleton node that has a draftRef, drawn from the
// node's own ref class, with refPrefix 'cr-ref-' and the divergence ledger, so a walk compares every mapped node on every
// property. The pairs themselves are lib/pairs.mjs::configText's (the same generator Solve's full-coverage walker uses):
// Fill writes the small base config that generator spreads, and the generator writes the pairs.
import { configText } from './pairs.mjs';
import { refOf, REF_PREFIX } from './tree.mjs';

// The pairs configText takes: { ref, draft } for each node with a draftRef (the finder as the skeleton wrote it, a
// walker finder on the whole draft page). tree: the filled tree (refs on every node); nodes: skeletonNodes( skeleton ).
export function walkerPairs( nodes, tree ) {
	const flat = [];
	const go = ( list ) => list.forEach( ( n ) => {
		flat.push( n );
		go( n.innerBlocks || [] );
	} );
	go( tree );
	return nodes.filter( ( n ) => undefined !== n.node.draftRef ).map( ( n ) => ( { ref: refOf( flat[ n.index ] ), draft: n.node.draftRef } ) );
}

// The base config: the draft and live pages, the walker states, the divergence ledger (a path relative to the config
// file) and refPrefix. `open` is the regex source of the text a single-page draft's navigation clicks. A local draft
// is served on a fresh port each time, so the draft url may be overridden with SGS_DRAFT_URL.
export function baseConfigText( { surface, draftUrl, liveUrl, open = null, divergences = null, state = 'opening' } ) {
	return [
		`// Generated by scripts/computed-route/fill.mjs for the ${ surface } surface: the draft and live pages, the walker state, and the`,
		'// divergence ledger. The pairs come from the skeleton\'s draftRef finders (lib/pairs.mjs::configText), in the file beside this one.',
		'// A draft served from a local folder listens on a new port per run: set SGS_DRAFT_URL to the address it is on now.',
		'export default {',
		`\tname: ${ JSON.stringify( surface ) },`,
		'\twidths: [ 375, 768, 1440, 1920 ],',
		`\trefPrefix: ${ JSON.stringify( REF_PREFIX ) },`,
		...( divergences ? [ `\tdivergences: ${ JSON.stringify( divergences ) },` ] : [] ),
		`\tdraft: { url: process.env.SGS_DRAFT_URL || ${ JSON.stringify( draftUrl ) }${ open ? `, open: ( h ) => h.clickText( ${ JSON.stringify( open ) }, { wait: 900 } )` : '' } },`,
		`\tlive: { url: ${ JSON.stringify( liveUrl ) } },`,
		`\tstates: [ { name: ${ JSON.stringify( state ) }, fullPage: true } ],`,
		'\tpairs: [],',
		'};',
		'',
	].join( '\n' );
}

// Both files' names and texts: { baseFile, baseText, fullFile, fullText }. The full file is what Solve and the walker run.
export function walkerConfigs( { surface, nodes, tree, draftUrl, liveUrl, open, divergences, state } ) {
	const baseFile = `${ surface }.fill-base.mjs`;
	return {
		baseFile,
		baseText: baseConfigText( { surface, draftUrl, liveUrl, open, divergences, state } ),
		fullFile: `${ surface }.fill.mjs`,
		fullText: configText( baseFile, surface, walkerPairs( nodes, tree ) ),
	};
}
