// Block pairing for full coverage (plan .claude/plans/2026-10-04-spec47-full-coverage.md): every block of a surface
// is paired with its draft element through the walker's word matcher, never through a guessed locator. A block's
// words are every live word inside it (nested blocks included); its draft partner is the smallest draft element
// holding the draft twins of those words. A pairing is kept only when it passes PAIRING_LIMITS.

// A pairing is doubtful, and left out, when the partner holds under `coverage` of the block's matched words, when it
// holds a matched word whose live twin sits outside the block, or when its box at 1440 is outside `boxRatio` of the
// block's box on either axis.
export const PAIRING_LIMITS = { coverage: 0.8, boxRatio: [ 0.5, 2 ], minWords: 1 };

// liveRefs[i]: the cr-ref classes around live word i, innermost first. Returns Map ref -> [live word indices].
export function wordsByBlock( liveRefs ) {
	const out = new Map();
	liveRefs.forEach( ( refs, i ) => ( refs || [] ).forEach( ( ref ) => {
		out.has( ref ) || out.set( ref, [] );
		out.get( ref ).push( i );
	} ) );
	return out;
}

// matches: [[draftIndex, liveIndex]] from matchWords. Returns Map ref -> { live: [i], draft: [j] } (the draft twins
// of the block's matched words).
export function twinsByBlock( matches, blocks ) {
	const twinOf = new Map( matches.map( ( [ d, l ] ) => [ l, d ] ) );
	const out = new Map();
	for ( const [ ref, live ] of blocks ) {
		out.set( ref, { live, draft: live.filter( ( i ) => twinOf.has( i ) ).map( ( i ) => twinOf.get( i ) ) } );
	}
	return out;
}

// Judges one pairing. block: { ref, live: [i], draft: [j], liveBox }; partner: { inside: [draft word indices inside
// it], box }; liveRefsOfDraft: Map draftIndex -> refs around its live twin. Returns { ok, why }.
export function judgePairing( block, partner, liveRefsOfDraft, limits = PAIRING_LIMITS ) {
	if ( block.draft.length < limits.minWords ) {
		return { ok: false, why: 'no matched words' };
	}
	const coverage = block.draft.length / block.live.length;
	if ( coverage < limits.coverage ) {
		return { ok: false, why: `only ${ Math.round( coverage * 100 ) }% of its words matched the draft` };
	}
	const foreign = partner.inside.filter( ( j ) => liveRefsOfDraft.has( j ) && ! liveRefsOfDraft.get( j ).includes( block.ref ) );
	if ( foreign.length ) {
		return { ok: false, why: `the draft element also holds ${ foreign.length } word(s) that belong outside this block` };
	}
	const [ lo, hi ] = limits.boxRatio;
	for ( const k of [ 'w', 'h' ] ) {
		const r = partner.box[ k ] / Math.max( 1, block.liveBox[ k ] );
		if ( r < lo || r > hi ) {
			return { ok: false, why: `its ${ 'w' === k ? 'width' : 'height' } is ${ partner.box[ k ] }px on the draft against ${ block.liveBox[ k ] }px live` };
		}
	}
	return { ok: true, why: null };
}

// The generated walker config: the hand config plus one pair per kept block. The hand config keeps its states, draft
// navigation, exclusions and divergence ledger; refPrefix is restated so Solve accepts the file.
export function configText( handFile, surface, pairs ) {
	const lines = pairs.map( ( p ) => `\t{ name: ${ JSON.stringify( `gen-${ p.ref.replace( /^cr-ref-/, '' ) }` ) }, text: false, structure: false, draft: ${ JSON.stringify( p.draft ) }, live: ${ JSON.stringify( `.${ p.ref }` ) } },` );
	return [
		`// Generated by scripts/computed-route/pairs.mjs for the ${ surface } surface: the hand config plus one pair per block,`,
		'// each paired with its draft element through matched words. Regenerate rather than edit.',
		`import base from './${ handFile }';`,
		'',
		'const generated = [',
		...lines,
		'];',
		'',
		'export default { ...base, refPrefix: base.refPrefix, pairs: [ ...base.pairs, ...generated ] };',
		'',
	].join( '\n' );
}
