<?php
/**
 * Title: Featured Product
 * Slug: sgs/featured-product
 * Categories: sgs
 * Description: Auto-registered from the .featured-product section of a clone run. Inner blocks: core/heading, core/paragraph, sgs/button, sgs/container, sgs/decorative-image.
 *
 * Auto-generated by sgs-clone pipeline +REGISTER tail.
 * Source clone run: mamas-munches-homepage-2026-05-13-104825
 * Generated: 2026-05-13T10:48:40.181974+00:00
 * Edits to this file may be overwritten on the next clone run --
 * author the source mockup instead.
 *
 * @package SGS\Theme
 */
?>

<!-- wp:sgs/container {"anchor":"featured-product","className":"sgs-featured-product"} -->
  <!-- wp:core/heading --><h2 class="wp-block-heading">Zookies — Our Signature Giant Cookie</h2><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>One Zookie is a proper sized treat. Every one baked to order, same week.</p><!-- /wp:core/paragraph -->
  <!-- wp:sgs/decorative-image {"imageUrl":"../../research/photography/wp-media-library/cookies-stacked.jpeg","imageAlt":"Stack of Mama's Munches Zookies lactation cookies"} /-->
  <!-- wp:core/heading {"level":3} --><h3 class="wp-block-heading">Mama's Munches Zookies</h3><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>Baked fresh every week and posted the same day. Oats, brewer's yeast, flaxseed, fenugreek — no shortcuts, no preservatives.</p><!-- /wp:core/paragraph -->
  <!-- wp:sgs/button {"label":"8-pack","url":"#"} /-->
  <!-- wp:sgs/button {"label":"12-pack","url":"#"} /-->
  <!-- wp:sgs/button {"label":"20-pack","url":"#"} /-->
  <!-- wp:sgs/button {"label":"40-pack","url":"#"} /-->
  <!-- wp:sgs/button {"label":"Add to Cart — £10","url":"/product/zookies/"} /-->
  <!-- wp:sgs/decorative-image {"imageUrl":"../../research/photography/wp-media-library/cookies-on-bun-case.jpeg","imageAlt":"Mama's Munches cookies in a bakery display"} /-->
  <!-- wp:core/heading {"level":3} --><h3 class="wp-block-heading">The Trial Pack</h3><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>Not sure yet? Try 3 Classic Zookies and see what all the mums are talking about. Postage included.</p><!-- /wp:core/paragraph -->
  <!-- wp:sgs/button {"label":"Try 3 for £5","url":"/product/trial-pack/"} /-->
<!-- /wp:sgs/container -->
