<?php
/**
 * Title: Footer
 * Slug: sgs/footer
 * Categories: sgs
 * Description: Auto-registered from the .footer section of a clone run. Inner blocks: core/heading, core/paragraph, sgs/container, sgs/decorative-image.
 *
 * Auto-generated by sgs-clone pipeline +REGISTER tail.
 * Source clone run: mamas-munches-homepage-2026-05-13-104825
 * Generated: 2026-05-13T10:48:40.216683+00:00
 * Edits to this file may be overwritten on the next clone run --
 * author the source mockup instead.
 *
 * @package SGS\Theme
 */
?>

<!-- wp:sgs/container {"anchor":"footer","className":"sgs-footer"} -->
  <!-- wp:sgs/decorative-image {"imageUrl":"../../research/brand/Mamas-Munches-Horizontal-Logo-2-305x102.webp","imageAlt":"Mama's Munches"} /-->
  <!-- wp:core/paragraph --><p>Real food for real mums. Handmade in Birmingham with care.</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>Birmingham, UK</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>Zainab@mamasmunches.com</p><!-- /wp:core/paragraph -->
  <!-- wp:core/heading {"level":5} --><h5 class="wp-block-heading">Shop</h5><!-- /wp:core/heading -->
  <!-- wp:core/heading {"level":5} --><h5 class="wp-block-heading">Information</h5><!-- /wp:core/heading -->
<!-- /wp:sgs/container -->
