<?php
/**
 * Title: Gift Section
 * Slug: sgs/gift-section
 * Categories: sgs
 * Description: Auto-registered from the .gift-section section of a clone run. Inner blocks: core/heading, core/paragraph, sgs/button, sgs/container.
 *
 * Auto-generated by sgs-clone pipeline +REGISTER tail.
 * Source clone run: mamas-munches-homepage-2026-05-13-104825
 * Generated: 2026-05-13T10:48:40.193380+00:00
 * Edits to this file may be overwritten on the next clone run --
 * author the source mockup instead.
 *
 * @package SGS\Theme
 */
?>

<!-- wp:sgs/container {"anchor":"gift-section","className":"sgs-gift-section"} -->
  <!-- wp:core/heading --><h2 class="wp-block-heading">A gift she'll actually use</h2><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>For baby showers, new arrivals, and the mums who deserve a treat.</p><!-- /wp:core/paragraph -->
  <!-- wp:core/heading {"level":3} --><h3 class="wp-block-heading">New Baby Gift Box</h3><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>The perfect gift for a new mum. A mix of Zookies and Classics in a gift box, ready to send.</p><!-- /wp:core/paragraph -->
  <!-- wp:sgs/button {"label":"Shop Gift Box","url":"/product/gift-box/"} /-->
  <!-- wp:core/heading {"level":3} --><h3 class="wp-block-heading">40-Day Care Bundle</h3><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>Six weekly deliveries for the 40-day postnatal window. One of the most thoughtful gifts you can give a new mum.</p><!-- /wp:core/paragraph -->
  <!-- wp:sgs/button {"label":"Shop Bundle","url":"/product/40-day-bundle/"} /-->
  <!-- wp:core/paragraph --><p>🏥 Heading to hospital? Ask us about our Send to Ward delivery.</p><!-- /wp:core/paragraph -->
<!-- /wp:sgs/container -->
