<?php
/**
 * Title: Header
 * Slug: sgs/header
 * Categories: sgs
 * Description: Auto-registered from the .header section of a clone run. Inner blocks: sgs/container, sgs/decorative-image.
 *
 * Auto-generated by sgs-clone pipeline +REGISTER tail.
 * Source clone run: mamas-munches-homepage-2026-05-13-104825
 * Generated: 2026-05-13T10:48:40.168692+00:00
 * Edits to this file may be overwritten on the next clone run --
 * author the source mockup instead.
 *
 * @package SGS\Theme
 */
?>

<!-- wp:sgs/container {"anchor":"header","className":"sgs-header"} -->
  <!-- wp:sgs/decorative-image {"imageUrl":"../../research/brand/Mamas-Munches-Horizontal-Logo-2-305x102.webp","imageAlt":"Mama's Munches"} /-->
<!-- /wp:sgs/container -->
