<?php
/**
 * Title: Social Proof
 * Slug: sgs/social-proof
 * Categories: sgs
 * Description: Auto-registered from the .social-proof section of a clone run. Inner blocks: core/heading, core/paragraph, sgs/container.
 *
 * Auto-generated by sgs-clone pipeline +REGISTER tail.
 * Source clone run: mamas-munches-homepage-2026-05-13-104825
 * Generated: 2026-05-13T10:48:40.205630+00:00
 * Edits to this file may be overwritten on the next clone run --
 * author the source mockup instead.
 *
 * @package SGS\Theme
 */
?>

<!-- wp:sgs/container {"anchor":"social-proof","className":"sgs-social-proof"} -->
  <!-- wp:core/heading --><h2 class="wp-block-heading">What mums are saying</h2><!-- /wp:core/heading -->
  <!-- wp:core/paragraph --><p>Real feedback from real mums — nothing fabricated.</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>"I was sceptical but honestly these have made such a difference. My supply picked up within a few days. And they actually taste amazing."</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>Reham, London</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>"Bought these for my best friend who was really struggling. She was in tears when they arrived — said they were the loveliest gift. And they did help."</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>Sarah M., Manchester</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>"Zainab is so responsive and lovely. The cookies arrived quickly and my daughter (new mum) absolutely loved them. Will order again and again."</p><!-- /wp:core/paragraph -->
  <!-- wp:core/paragraph --><p>Halimah, Birmingham</p><!-- /wp:core/paragraph -->
<!-- /wp:sgs/container -->
